//! BTM configuration types — btm.toml format.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Type alias — BTM settings use the shared config settings from core.
pub type BtmSettings = contour_core::ConfigSettings;

/// BTM configuration file (btm.toml).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BtmConfig {
    pub settings: BtmSettings,
    #[serde(default)]
    pub apps: Vec<BtmAppEntry>,
}

/// A BTM rule for the service management payload.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BtmRule {
    pub rule_type: String,
    pub rule_value: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

/// An application entry in a BTM configuration file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BtmAppEntry {
    pub name: String,
    pub bundle_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub team_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code_requirement: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub rules: Vec<BtmRule>,
}

impl BtmConfig {
    pub fn load(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("Failed to read {}: {e}", path.display()))?;
        toml::from_str(&content)
            .map_err(|e| anyhow::anyhow!("Failed to parse btm.toml from {}: {e}", path.display()))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let content = toml::to_string_pretty(self)
            .map_err(|e| anyhow::anyhow!("Failed to serialize btm.toml: {e}"))?;
        let with_header = format!(
            "# BTM Policy Definitions\n\
             # Generated by: contour btm\n\
             # Edit manually or re-run scan to update\n\n\
             {content}"
        );
        std::fs::write(path, with_header)
            .map_err(|e| anyhow::anyhow!("Failed to write {}: {e}", path.display()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_btm_config_roundtrip() {
        let config = BtmConfig {
            settings: BtmSettings {
                org: "com.example".to_string(),
                display_name: Some("Test Profile".to_string()),
            },
            apps: vec![BtmAppEntry {
                name: "Zoom".to_string(),
                bundle_id: "us.zoom.xos".to_string(),
                team_id: Some("BJ4HAAB9B3".to_string()),
                code_requirement: None,
                rules: vec![BtmRule {
                    rule_type: "TeamIdentifier".to_string(),
                    rule_value: "BJ4HAAB9B3".to_string(),
                    comment: Some("Zoom".to_string()),
                }],
            }],
        };

        let toml_str = toml::to_string_pretty(&config).unwrap();
        let parsed: BtmConfig = toml::from_str(&toml_str).unwrap();

        assert_eq!(parsed.settings.org, "com.example");
        assert_eq!(
            parsed.settings.display_name,
            Some("Test Profile".to_string())
        );
        assert_eq!(parsed.apps.len(), 1);
        assert_eq!(parsed.apps[0].bundle_id, "us.zoom.xos");
        assert_eq!(parsed.apps[0].rules.len(), 1);
        assert_eq!(parsed.apps[0].rules[0].rule_type, "TeamIdentifier");
    }
}
