//! Notification configuration types — notifications.toml format.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Type alias — notification settings use the shared config settings from core.
pub type NotificationSettings = contour_core::ConfigSettings;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationConfig {
    pub settings: NotificationSettings,
    #[serde(default)]
    pub apps: Vec<NotificationAppEntry>,
}

/// Per-app notification settings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationAppEntry {
    pub name: String,
    pub bundle_id: String,
    #[serde(default = "default_true")]
    pub alerts_enabled: bool,
    /// 0 = None, 1 = Temporary Banner, 2 = Persistent Banner
    #[serde(default = "default_alert_type")]
    pub alert_type: u8,
    #[serde(default = "default_true")]
    pub badges_enabled: bool,
    #[serde(default = "default_true")]
    pub critical_alerts: bool,
    #[serde(default = "default_true")]
    pub lock_screen: bool,
    #[serde(default = "default_true")]
    pub notification_center: bool,
    #[serde(default)]
    pub sounds_enabled: bool,
}

fn default_true() -> bool {
    true
}
fn default_alert_type() -> u8 {
    1
}

impl NotificationConfig {
    pub fn load(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("Failed to read {}: {e}", path.display()))?;
        toml::from_str(&content)
            .map_err(|e| anyhow::anyhow!("Failed to parse notifications.toml: {e}"))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let content = toml::to_string_pretty(self)
            .map_err(|e| anyhow::anyhow!("Failed to serialize notifications.toml: {e}"))?;
        let with_header = format!(
            "# Notification Settings Definitions\n\
             # Generated by: contour notifications\n\
             # Edit manually or re-run scan to update\n\n\
             {content}"
        );
        std::fs::write(path, with_header)
            .map_err(|e| anyhow::anyhow!("Failed to write {}: {e}", path.display()))
    }
}

impl NotificationAppEntry {
    /// Create a new entry with all notifications enabled (sensible defaults).
    pub fn new(name: String, bundle_id: String) -> Self {
        Self {
            name,
            bundle_id,
            alerts_enabled: true,
            alert_type: 1,
            badges_enabled: true,
            critical_alerts: true,
            lock_screen: true,
            notification_center: true,
            sounds_enabled: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_notification_config_roundtrip() {
        let config = NotificationConfig {
            settings: NotificationSettings {
                org: "com.example".to_string(),
                display_name: Some("Test".to_string()),
            },
            apps: vec![NotificationAppEntry {
                name: "Slack".to_string(),
                bundle_id: "com.tinyspeck.slackmacgap".to_string(),
                alerts_enabled: true,
                alert_type: 2,
                badges_enabled: true,
                critical_alerts: false,
                lock_screen: true,
                notification_center: true,
                sounds_enabled: true,
            }],
        };
        let toml_str = toml::to_string_pretty(&config).unwrap();
        let parsed: NotificationConfig = toml::from_str(&toml_str).unwrap();
        assert_eq!(parsed.settings.org, "com.example");
        assert_eq!(parsed.apps.len(), 1);
        assert_eq!(parsed.apps[0].alert_type, 2);
        assert!(parsed.apps[0].sounds_enabled);
        assert!(!parsed.apps[0].critical_alerts);
    }

    #[test]
    fn test_notification_app_entry_defaults() {
        let entry = NotificationAppEntry::new("Test".to_string(), "com.test".to_string());
        assert!(entry.alerts_enabled);
        assert_eq!(entry.alert_type, 1);
        assert!(entry.badges_enabled);
        assert!(entry.critical_alerts);
        assert!(entry.lock_screen);
        assert!(entry.notification_center);
        assert!(!entry.sounds_enabled);
    }
}
