//! Fleet policy generator — osquery detection queries from mSCP rules.
//!
//! For each mSCP rule with `mobileconfig: true` and `mobileconfig_info`, generates
//! a Fleet policy YAML entry using osquery's `managed_policies` table. This provides
//! the "detection" side to complement the existing "enforcement" side
//! (profiles + scripts).

use crate::managers::OdvOverrides;
use crate::models::MscpRule;
use anyhow::{Context, Result};
use serde::Serialize;
use std::path::{Path, PathBuf};

/// A generated Fleet policy (osquery `managed_policies` query)
#[derive(Debug, Clone, Serialize)]
pub struct FleetPolicy {
    pub name: String,
    pub description: String,
    pub query: String,
    pub platform: String,
    pub critical: bool,
    pub calendar_events_enabled: bool,
}

/// Generator that converts mSCP mobileconfig rules into Fleet policy YAML
#[derive(Debug)]
pub struct FleetPolicyGenerator {
    #[expect(dead_code, reason = "Reserved for future use in diagnostic output")]
    baseline_name: String,
}

impl FleetPolicyGenerator {
    pub fn new(baseline_name: &str) -> Self {
        Self {
            baseline_name: baseline_name.to_string(),
        }
    }

    /// Generate Fleet policies for all eligible rules in a baseline.
    ///
    /// Writes a YAML array to `{output_dir}/{baseline}_policies.yml` and returns
    /// the generated policies plus the path to the written file.
    pub fn generate_for_baseline(
        &self,
        rules: &[MscpRule],
        baseline_name: &str,
        odv_manager: Option<&OdvOverrides>,
        output_dir: &Path,
    ) -> Result<(Vec<FleetPolicy>, PathBuf)> {
        let mut policies = Vec::new();

        for rule in rules {
            if let Some(policy) = self.generate_policy_for_rule(rule, baseline_name, odv_manager) {
                policies.push(policy);
            }
        }

        let file_path = output_dir.join(format!("{baseline_name}_policies.yml"));

        if !policies.is_empty() {
            std::fs::create_dir_all(output_dir).with_context(|| {
                format!("Failed to create policies dir: {}", output_dir.display())
            })?;

            let yaml_content = yaml_serde::to_string(&policies)
                .context("Failed to serialize Fleet policies to YAML")?;

            let header = format!(
                "# Fleet Policies — osquery managed_policies detection queries\n\
                 # Baseline: {baseline_name}\n\
                 #\n\
                 # Generated by contour mscp — https://github.com/headmin/contour\n\n"
            );

            std::fs::write(&file_path, format!("{header}{yaml_content}"))
                .with_context(|| format!("Failed to write policy file: {}", file_path.display()))?;
        }

        Ok((policies, file_path))
    }

    /// Try to generate a single Fleet policy from an mSCP rule.
    ///
    /// Returns `None` when the rule cannot be converted (no mobileconfig_info,
    /// unresolvable `$ODV`, array values only, etc.).
    fn generate_policy_for_rule(
        &self,
        rule: &MscpRule,
        baseline_name: &str,
        odv_manager: Option<&OdvOverrides>,
    ) -> Option<FleetPolicy> {
        // Gate: must have mobileconfig: true with info
        if !rule.mobileconfig || rule.mobileconfig_info.is_none() {
            return None;
        }

        let info = rule.mobileconfig_info.as_ref()?;
        let info_map = info.as_mapping()?;

        let mut where_clauses: Vec<String> = Vec::new();

        for (domain_key, domain_value) in info_map {
            let domain_str = domain_key.as_str()?;
            let kv_map = domain_value.as_mapping()?;

            // Handle nested ManagedClient.preferences domains
            let (effective_domain, effective_kvs) =
                if domain_str == "com.apple.ManagedClient.preferences" {
                    // The value is { inner_domain: { key: val, ... } }
                    if let Some((inner_domain_key, inner_domain_val)) = kv_map.iter().next() {
                        let inner_domain = inner_domain_key.as_str()?;
                        let inner_kvs = inner_domain_val.as_mapping()?;
                        (inner_domain, inner_kvs)
                    } else {
                        continue;
                    }
                } else {
                    (domain_str, kv_map)
                };

            for (key, value) in effective_kvs {
                let key_str = key.as_str()?;
                let resolved = self.resolve_value(value, rule, baseline_name, odv_manager);

                let resolved = match resolved {
                    Some(v) => v,
                    None => {
                        tracing::warn!(
                            "Skipping {}.{} in rule {} — unresolvable $ODV",
                            effective_domain,
                            key_str,
                            rule.id
                        );
                        continue;
                    }
                };

                let clause = self.build_where_clause(effective_domain, key_str, &resolved);
                if let Some(c) = clause {
                    where_clauses.push(c);
                }
            }
        }

        if where_clauses.is_empty() {
            return None;
        }

        // Build the final query — one policy per rule.
        // Multiple key-value pairs → INTERSECT subqueries.
        let query = if where_clauses.len() == 1 {
            format!("{};", where_clauses[0])
        } else {
            where_clauses.join("\nINTERSECT\n") + ";"
        };

        let title = sanitize_title(&rule.title);
        let title = if title.contains("$ODV") {
            if let Some(resolved) = self.resolve_odv(rule, baseline_name, odv_manager) {
                title.replace("$ODV", &resolved_value_to_string(&resolved))
            } else {
                title.replace("$ODV", "N")
            }
        } else {
            title
        };

        Some(FleetPolicy {
            name: format!("mSCP - {title}"),
            description: format!(
                "Verify {} is enforced via managed profile ({})",
                title, rule.id
            ),
            query,
            platform: "darwin".to_string(),
            critical: false,
            calendar_events_enabled: false,
        })
    }

    /// Resolve a YAML value, substituting `$ODV` if needed.
    ///
    /// Returns `None` when `$ODV` cannot be resolved.
    fn resolve_value(
        &self,
        value: &yaml_serde::Value,
        rule: &MscpRule,
        baseline_name: &str,
        odv_manager: Option<&OdvOverrides>,
    ) -> Option<ResolvedValue> {
        match value {
            yaml_serde::Value::String(s) if s.contains("$ODV") => {
                let resolved = self.resolve_odv(rule, baseline_name, odv_manager)?;
                Some(resolved)
            }
            yaml_serde::Value::Bool(b) => Some(ResolvedValue::Bool(*b)),
            yaml_serde::Value::Number(n) => {
                if let Some(i) = n.as_i64() {
                    Some(ResolvedValue::Integer(i))
                } else if let Some(f) = n.as_f64() {
                    Some(ResolvedValue::Integer(f as i64))
                } else {
                    Some(ResolvedValue::Str(n.to_string()))
                }
            }
            yaml_serde::Value::String(s) => Some(ResolvedValue::Str(s.clone())),
            yaml_serde::Value::Sequence(_) => {
                // Skip array values — can't express in managed_policies row check
                tracing::debug!(
                    "Skipping array value in rule {} — not supported in managed_policies check",
                    rule.id
                );
                None
            }
            _ => None,
        }
    }

    /// Resolve `$ODV` for a rule: OdvOverrides → rule.odv.{baseline} → rule.odv.recommended
    fn resolve_odv(
        &self,
        rule: &MscpRule,
        baseline_name: &str,
        odv_manager: Option<&OdvOverrides>,
    ) -> Option<ResolvedValue> {
        // First, try OdvOverrides (has user overrides)
        if let Some(mgr) = odv_manager {
            if let Some(val) = mgr.get_value(&rule.id) {
                return yaml_value_to_resolved(val);
            }
        }

        // Fall back to rule's own odv field
        if let Some(ref odv) = rule.odv {
            if let Some(odv_map) = odv.as_mapping() {
                // Try baseline-specific first
                let baseline_key = yaml_serde::Value::String(baseline_name.to_string());
                if let Some(val) = odv_map.get(&baseline_key) {
                    return yaml_value_to_resolved(val);
                }

                // Try "recommended" fallback
                let rec_key = yaml_serde::Value::String("recommended".to_string());
                if let Some(val) = odv_map.get(&rec_key) {
                    return yaml_value_to_resolved(val);
                }
            }
        }

        None
    }

    /// Build a SQL WHERE clause for `managed_policies` from a single key-value pair.
    ///
    /// Returns `None` for values that can't be expressed (arrays, mappings).
    fn build_where_clause(&self, domain: &str, key: &str, value: &ResolvedValue) -> Option<String> {
        let value_expr = match value {
            ResolvedValue::Bool(b) => {
                let v = if *b { "1" } else { "0" };
                format!("value = '{v}'")
            }
            ResolvedValue::Integer(i) => {
                format!("CAST(value AS INTEGER) = {i}")
            }
            ResolvedValue::Str(s) => {
                // Escape single quotes for SQL safety
                let escaped = s.replace('\'', "''");
                format!("value = '{escaped}'")
            }
        };

        Some(format!(
            "SELECT 1 FROM managed_policies WHERE domain = '{domain}' AND name = '{key}' AND {value_expr}"
        ))
    }
}

/// Internal resolved value type for building SQL clauses
#[derive(Debug, Clone)]
enum ResolvedValue {
    Bool(bool),
    Integer(i64),
    Str(String),
}

/// Convert a `yaml_serde::Value` to a `ResolvedValue`
fn yaml_value_to_resolved(val: &yaml_serde::Value) -> Option<ResolvedValue> {
    match val {
        yaml_serde::Value::Bool(b) => Some(ResolvedValue::Bool(*b)),
        yaml_serde::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                Some(ResolvedValue::Integer(i))
            } else if let Some(f) = n.as_f64() {
                Some(ResolvedValue::Integer(f as i64))
            } else {
                Some(ResolvedValue::Str(n.to_string()))
            }
        }
        yaml_serde::Value::String(s) => Some(ResolvedValue::Str(s.clone())),
        yaml_serde::Value::Sequence(_) | yaml_serde::Value::Mapping(_) => None,
        yaml_serde::Value::Null => None,
        yaml_serde::Value::Tagged(t) => yaml_value_to_resolved(&t.value),
    }
}

/// Convert a `ResolvedValue` to a display string for use in titles/descriptions
fn resolved_value_to_string(val: &ResolvedValue) -> String {
    match val {
        ResolvedValue::Bool(b) => b.to_string(),
        ResolvedValue::Integer(i) => i.to_string(),
        ResolvedValue::Str(s) => s.clone(),
    }
}

/// Sanitize a rule title for use in a Fleet policy name
fn sanitize_title(title: &str) -> String {
    // Remove leading/trailing whitespace, collapse internal whitespace
    title.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn make_rule(id: &str, title: &str, mobileconfig_info: Option<yaml_serde::Value>) -> MscpRule {
        MscpRule {
            id: id.to_string(),
            title: title.to_string(),
            discussion: String::new(),
            check: None,
            result: None,
            fix: None,
            references: HashMap::new(),
            macos: vec![],
            tags: vec![],
            severity: None,
            mobileconfig: mobileconfig_info.is_some(),
            mobileconfig_info,
            odv: None,
        }
    }

    #[test]
    fn test_simple_boolean_policy() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "askForPassword": true
            }
        }))
        .unwrap();

        let rule = make_rule(
            "screensaver_ask",
            "Enforce Screen Saver Password",
            Some(info),
        );
        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        assert_eq!(p.platform, "darwin");
        assert!(p.query.contains("managed_policies"));
        assert!(p.query.contains("com.apple.screensaver"));
        assert!(p.query.contains("askForPassword"));
        assert!(p.query.contains("'1'"));
    }

    #[test]
    fn test_integer_value_policy() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "idleTime": 1200
            }
        }))
        .unwrap();

        let rule = make_rule(
            "screensaver_idle",
            "Enforce Screen Saver Timeout",
            Some(info),
        );
        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        assert!(p.query.contains("CAST(value AS INTEGER) = 1200"));
    }

    #[test]
    fn test_multiple_keys_intersect() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "askForPassword": true,
                "idleTime": 1200
            }
        }))
        .unwrap();

        let rule = make_rule("screensaver_multi", "Enforce Screen Saver", Some(info));
        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        assert!(p.query.contains("INTERSECT"));
    }

    #[test]
    fn test_skip_non_mobileconfig() {
        let rule = make_rule("script_rule", "Script Only Rule", None);
        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);
        assert!(policy.is_none());
    }

    #[test]
    fn test_odv_resolution_from_rule() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "idleTime": "$ODV"
            }
        }))
        .unwrap();

        let odv = yaml_serde::to_value(serde_json::json!({
            "hint": "Max idle time",
            "recommended": 1200,
            "cis_lvl1": 600
        }))
        .unwrap();

        let mut rule = make_rule(
            "screensaver_odv",
            "Enforce Screen Saver Timeout",
            Some(info),
        );
        rule.odv = Some(odv);

        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        // Should use cis_lvl1-specific value (600), not recommended (1200)
        assert!(p.query.contains("600"), "query was: {}", p.query);
    }

    #[test]
    fn test_odv_fallback_to_recommended() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "idleTime": "$ODV"
            }
        }))
        .unwrap();

        let odv = yaml_serde::to_value(serde_json::json!({
            "hint": "Max idle time",
            "recommended": 1200
        }))
        .unwrap();

        let mut rule = make_rule(
            "screensaver_odv",
            "Enforce Screen Saver Timeout",
            Some(info),
        );
        rule.odv = Some(odv);

        let generator = FleetPolicyGenerator::new("cis_lvl2");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl2", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        // No cis_lvl2 key, should fall back to recommended (1200)
        assert!(p.query.contains("1200"), "query was: {}", p.query);
    }

    #[test]
    fn test_skip_unresolvable_odv() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "idleTime": "$ODV"
            }
        }))
        .unwrap();

        // No ODV field at all
        let rule = make_rule(
            "screensaver_no_odv",
            "Enforce Screen Saver Timeout",
            Some(info),
        );

        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        // All values were $ODV with no resolution → skip
        assert!(policy.is_none());
    }

    #[test]
    fn test_string_value_policy() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.Safari": {
                "HomePage": "https://example.com"
            }
        }))
        .unwrap();

        let rule = make_rule("safari_homepage", "Set Safari Homepage", Some(info));
        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        assert!(p.query.contains("value = 'https://example.com'"));
    }

    #[test]
    fn test_generate_for_baseline() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "askForPassword": true
            }
        }))
        .unwrap();

        let rules = vec![
            make_rule(
                "screensaver_ask",
                "Enforce Screen Saver Password",
                Some(info),
            ),
            make_rule("script_only", "Script Only Rule", None),
        ];

        let temp_dir = tempfile::TempDir::new().unwrap();
        let output_dir = temp_dir.path().join("policies");

        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let (policies, path) = generator
            .generate_for_baseline(&rules, "cis_lvl1", None, &output_dir)
            .unwrap();

        assert_eq!(policies.len(), 1);
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("managed_policies"));
        assert!(content.contains("mSCP - Enforce Screen Saver Password"));
    }

    #[test]
    fn test_managed_client_preferences_nesting() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.ManagedClient.preferences": {
                "com.apple.loginwindow": {
                    "DisableConsoleAccess": true
                }
            }
        }))
        .unwrap();

        let rule = make_rule("loginwindow", "Disable Console Access", Some(info));
        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        // Should use the inner domain, not ManagedClient.preferences
        assert!(p.query.contains("com.apple.loginwindow"));
        assert!(!p.query.contains("ManagedClient"));
        assert!(p.query.contains("DisableConsoleAccess"));
    }

    #[test]
    fn test_odv_in_title_resolved() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "idleTime": "$ODV"
            }
        }))
        .unwrap();

        let odv = yaml_serde::to_value(serde_json::json!({
            "hint": "Max idle time in seconds",
            "recommended": 1200,
            "cis_lvl2": 60
        }))
        .unwrap();

        let mut rule = make_rule(
            "screensaver_odv_title",
            "Restrict Screen Saver Timeout to $ODV Seconds",
            Some(info),
        );
        rule.odv = Some(odv);

        let generator = FleetPolicyGenerator::new("cis_lvl2");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl2", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        // Title should have $ODV replaced with the resolved value
        assert!(
            !p.name.contains("$ODV"),
            "name still contains $ODV: {}",
            p.name
        );
        assert!(
            !p.description.contains("$ODV"),
            "description still contains $ODV: {}",
            p.description
        );
        assert!(
            p.name.contains("60"),
            "name should contain resolved value 60: {}",
            p.name
        );
    }

    #[test]
    fn test_odv_in_title_fallback_when_unresolvable() {
        let info = yaml_serde::to_value(serde_json::json!({
            "com.apple.screensaver": {
                "askForPassword": true
            }
        }))
        .unwrap();

        // Rule has $ODV in title but no odv field and the mobileconfig value is not $ODV
        let rule = make_rule(
            "screensaver_no_odv_title",
            "Restrict Timeout to $ODV Days",
            Some(info),
        );

        let generator = FleetPolicyGenerator::new("cis_lvl1");
        let policy = generator.generate_policy_for_rule(&rule, "cis_lvl1", None);

        assert!(policy.is_some());
        let p = policy.unwrap();
        // $ODV should be replaced with fallback "N", not left as literal
        assert!(
            !p.name.contains("$ODV"),
            "name still contains $ODV: {}",
            p.name
        );
        assert!(
            p.name.contains('N'),
            "name should contain fallback 'N': {}",
            p.name
        );
    }

    #[test]
    fn test_empty_baseline_produces_no_file() {
        let rules: Vec<MscpRule> = vec![];

        let temp_dir = tempfile::TempDir::new().unwrap();
        let output_dir = temp_dir.path().join("policies");

        let generator = FleetPolicyGenerator::new("empty");
        let (policies, path) = generator
            .generate_for_baseline(&rules, "empty", None, &output_dir)
            .unwrap();

        assert!(policies.is_empty());
        assert!(!path.exists());
    }
}
