use super::script_helpers::{self, extract_check_scripts, extract_rule_scripts};
use crate::models::MscpRule;
use anyhow::{Context, Result};
use plist::Dictionary;
use std::fs;
use std::path::{Path, PathBuf};

/// Options for Munki script nopkg generation
#[derive(Debug, Clone)]
pub struct MunkiScriptOptions {
    /// Munki catalog to use (e.g., "production", "testing")
    pub catalog: String,

    /// Category for Munki items
    pub category: String,

    /// Display name prefix (e.g., "mSCP CIS L1")
    #[allow(dead_code, reason = "reserved for future use")]
    pub display_name_prefix: String,

    /// Whether to embed fix in installcheck (default) or use separate postinstall
    pub embed_fix_in_installcheck: bool,
}

impl Default for MunkiScriptOptions {
    fn default() -> Self {
        Self {
            catalog: super::munki_compliance::DEFAULT_MUNKI_CATALOG.to_string(),
            category: super::munki_compliance::DEFAULT_MUNKI_CATEGORY.to_string(),
            display_name_prefix: "mSCP".to_string(),
            embed_fix_in_installcheck: true,
        }
    }
}

/// Generator for Munki nopkg items from mSCP script rules
#[derive(Debug)]
pub struct MunkiScriptGenerator {
    options: MunkiScriptOptions,
}

impl MunkiScriptGenerator {
    pub fn new(options: MunkiScriptOptions) -> Self {
        Self { options }
    }

    /// Generate Munki nopkg pkginfo for a single rule
    /// Format matches munki-mscp-generator output
    pub fn generate_nopkg_for_rule(
        &self,
        rule: &MscpRule,
        _baseline_name: &str,
    ) -> Result<Dictionary> {
        if !rule.has_script_remediation() {
            anyhow::bail!("Rule {} does not have both check and fix scripts", rule.id);
        }

        if !rule.has_executable_fix() {
            anyhow::bail!("Rule {} fix is not an executable script", rule.id);
        }

        let mut dict = Dictionary::new();

        // Basic info - matches munki-mscp-generator format
        // name: just the rule ID (e.g., "audit_acls_files_configure")
        dict.insert("name".to_string(), plist::Value::String(rule.id.clone()));

        // display_name: rule title (mapped from mSCP title field)
        dict.insert(
            "display_name".to_string(),
            plist::Value::String(rule.title.clone()),
        );

        // description: rule discussion (mapped from mSCP discussion field)
        dict.insert(
            "description".to_string(),
            plist::Value::String(rule.discussion.clone()),
        );

        dict.insert(
            "version".to_string(),
            plist::Value::String("1.0".to_string()),
        );

        dict.insert(
            "installer_type".to_string(),
            plist::Value::String("nopkg".to_string()),
        );

        dict.insert("uninstallable".to_string(), plist::Value::Boolean(false));

        dict.insert(
            "unattended_install".to_string(),
            plist::Value::Boolean(true),
        );

        // Catalogs
        let catalogs = vec![plist::Value::String(self.options.catalog.clone())];
        dict.insert("catalogs".to_string(), plist::Value::Array(catalogs));

        // Category
        dict.insert(
            "category".to_string(),
            plist::Value::String(self.options.category.clone()),
        );

        // Generate scripts
        if self.options.embed_fix_in_installcheck {
            // Approach 1: Embed both check and fix in installcheck_script
            let installcheck = self.generate_combined_installcheck(rule)?;
            dict.insert(
                "installcheck_script".to_string(),
                plist::Value::String(installcheck),
            );

            // Dummy postinstall (Munki requires something to "install")
            dict.insert(
                "postinstall_script".to_string(),
                plist::Value::String("#!/bin/bash\nexit 0\n".to_string()),
            );
        } else {
            // Approach 2: Separate check and fix
            let installcheck = self.generate_installcheck_script(rule)?;
            dict.insert(
                "installcheck_script".to_string(),
                plist::Value::String(installcheck),
            );

            let postinstall = self.generate_postinstall_script(rule)?;
            dict.insert(
                "postinstall_script".to_string(),
                plist::Value::String(postinstall),
            );
        }

        Ok(dict)
    }

    /// Generate combined installcheck script (check + fix)
    /// This approach runs the fix immediately if check fails
    fn generate_combined_installcheck(&self, rule: &MscpRule) -> Result<String> {
        let scripts = extract_rule_scripts(rule)?;

        Ok(format!(
            r#"#!/bin/bash
# Combined installcheck and fix for rule: {}
# Generated by contour mscp

# Function to run the check
check_compliance() {{
{}
}}

# Function to run the fix
apply_fix() {{
{}
}}

# Run the check
CHECK_RESULT=$(check_compliance 2>&1)
CHECK_EXIT=$?

# Compare result
EXPECTED="{}"

# Check if compliant
if [[ "$CHECK_RESULT" == "$EXPECTED" ]] && [[ $CHECK_EXIT -eq 0 ]]; then
    # Compliant - no installation needed
    exit 1
else
    # Non-compliant - apply fix immediately
    echo "Rule {} non-compliant. Applying fix..."
    apply_fix

    # Verify fix was successful
    CHECK_RESULT_AFTER=$(check_compliance 2>&1)
    if [[ "$CHECK_RESULT_AFTER" == "$EXPECTED" ]]; then
        echo "Fix applied successfully"
        # Still exit 1 so Munki doesn't show this in UI
        exit 1
    else
        echo "Warning: Fix may not have been fully successful"
        exit 1
    fi
fi
"#,
            rule.id, scripts.check, scripts.fix, scripts.expected, rule.id
        ))
    }

    /// Generate installcheck script (check only)
    fn generate_installcheck_script(&self, rule: &MscpRule) -> Result<String> {
        let (check, expected) = extract_check_scripts(rule)?;

        Ok(format!(
            r#"#!/bin/bash
# Installcheck script for rule: {}
# Generated by contour mscp

# Run the check
CHECK_RESULT=$({} 2>&1)
CHECK_EXIT=$?

# Expected result
EXPECTED="{}"

# Compare result
if [[ "$CHECK_RESULT" == "$EXPECTED" ]] && [[ $CHECK_EXIT -eq 0 ]]; then
    # Compliant - no installation needed
    exit 1
else
    # Non-compliant - installation needed
    exit 0
fi
"#,
            rule.id, check, expected
        ))
    }

    /// Generate postinstall script (fix only)
    fn generate_postinstall_script(&self, rule: &MscpRule) -> Result<String> {
        let fix = rule.get_fix_script().context("Missing fix script")?;

        Ok(format!(
            r#"#!/bin/bash
# Postinstall script for rule: {}
# Generated by contour mscp

echo "Applying fix for rule: {}"

# Run the fix
{}

exit 0
"#,
            rule.id, rule.id, fix
        ))
    }

    /// Write pkginfo to file
    pub fn write_pkginfo<P: AsRef<Path>>(
        &self,
        pkginfo: &Dictionary,
        output_path: P,
    ) -> Result<()> {
        let path = output_path.as_ref();

        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        // Write as XML plist
        let mut file = fs::File::create(path)?;
        plist::to_writer_xml(&mut file, pkginfo).context("Failed to write pkginfo plist")?;

        Ok(())
    }

    /// Generate nopkg items for all script rules in a baseline
    pub fn generate_for_baseline<P: AsRef<Path>>(
        &self,
        rules: &[MscpRule],
        baseline_name: &str,
        output_dir: P,
    ) -> Result<Vec<PathBuf>> {
        let mut generated_paths = Vec::new();

        let script_rules = script_helpers::script_rules_for_baseline(rules, baseline_name);

        tracing::info!(
            "Found {} script-based remediation rules for baseline '{}'",
            script_rules.len(),
            baseline_name
        );

        for rule in script_rules {
            match self.generate_nopkg_for_rule(rule, baseline_name) {
                Ok(pkginfo) => {
                    // Filename matches munki-mscp-generator: just {rule_id}.plist
                    let filename = format!("{}.plist", rule.id);
                    let output_path = output_dir.as_ref().join(&filename);

                    match self.write_pkginfo(&pkginfo, &output_path) {
                        Ok(()) => {
                            tracing::info!(
                                "Generated nopkg for rule {}: {}",
                                rule.id,
                                output_path.display()
                            );
                            generated_paths.push(output_path);
                        }
                        Err(e) => {
                            tracing::warn!("Failed to write nopkg for rule {}: {}", rule.id, e);
                        }
                    }
                }
                Err(e) => {
                    tracing::warn!("Failed to generate nopkg for rule {}: {}", rule.id, e);
                }
            }
        }

        Ok(generated_paths)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transformers::script_helpers::create_test_rule;

    #[test]
    fn test_generate_nopkg() {
        let generator = MunkiScriptGenerator::new(MunkiScriptOptions::default());
        let rule = create_test_rule();

        let pkginfo = generator
            .generate_nopkg_for_rule(&rule, "cis_lvl1")
            .unwrap();

        // Name matches munki-mscp-generator format: just the rule ID
        assert_eq!(
            pkginfo.get("name").and_then(|v| v.as_string()),
            Some("audit_acls_files_configure")
        );

        assert_eq!(
            pkginfo.get("installer_type").and_then(|v| v.as_string()),
            Some("nopkg")
        );

        assert!(pkginfo.contains_key("installcheck_script"));
        assert!(pkginfo.contains_key("postinstall_script"));
    }

    #[test]
    fn test_combined_installcheck() {
        let generator = MunkiScriptGenerator::new(MunkiScriptOptions::default());
        let rule = create_test_rule();

        let script = generator.generate_combined_installcheck(&rule).unwrap();

        assert!(script.contains("check_compliance"));
        assert!(script.contains("apply_fix"));
        assert!(script.contains("/bin/chmod -RN /var/audit"));
    }
}
