use super::script_helpers::{
    self, audit_script, audit_summary, bundled_check_fn, bundled_remediate_fn,
    extract_check_scripts, extract_rule_scripts, remediate_script, remediate_summary,
    script_header, write_executable,
};
use crate::models::MscpRule;
use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

/// Script generation mode
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code, reason = "reserved for future use")]
pub enum ScriptMode {
    /// One combined script with all rules
    Combined,
    /// Individual script per rule (70 scripts for `cis_lvl1`)
    Granular,
    /// Bundled by category prefix (e.g., audit_*, os_*, `system_settings`_*)
    Bundled,
    /// Both granular and bundled
    Both,
}

/// Options for rule-based script generation (platform-agnostic)
#[derive(Debug, Clone)]
pub struct RuleScriptOptions {
    /// Script generation mode
    pub mode: ScriptMode,

    /// Script prefix for naming
    #[allow(dead_code, reason = "reserved for future use")]
    pub script_prefix: String,
}

impl Default for RuleScriptOptions {
    fn default() -> Self {
        Self {
            mode: ScriptMode::Bundled,
            script_prefix: "mscp".to_string(),
        }
    }
}

/// Generator for self-contained bash scripts from mSCP rules, grouped by category.
/// Platform-agnostic — output works for Fleet, Jamf, Munki, or any MDM that runs bash.
#[derive(Debug)]
pub struct RuleScriptGenerator {
    options: RuleScriptOptions,
}

impl RuleScriptGenerator {
    pub fn new(options: RuleScriptOptions) -> Self {
        Self { options }
    }

    /// Generate individual audit/remediate scripts for a single rule
    /// Returns (`audit_script_path`, `remediate_script_path`)
    pub fn generate_scripts_for_rule(
        &self,
        rule: &MscpRule,
        baseline_name: &str,
        output_dir: &Path,
    ) -> Result<(PathBuf, PathBuf)> {
        if !rule.has_script_remediation() {
            anyhow::bail!("Rule {} does not have both check and fix scripts", rule.id);
        }

        if !rule.has_executable_fix() {
            anyhow::bail!("Rule {} fix is not an executable script", rule.id);
        }

        // Create scripts directory
        fs::create_dir_all(output_dir)?;

        // Generate and write audit script
        let audit_content = self.generate_audit_script(rule)?;
        let audit_filename = format!("{}_{}_audit.sh", baseline_name, rule.id);
        let audit_path = output_dir.join(&audit_filename);
        write_executable(&audit_path, &audit_content)?;

        // Generate and write remediate script
        let remediate_content = self.generate_remediate_script(rule)?;
        let remediate_filename = format!("{}_{}_remediate.sh", baseline_name, rule.id);
        let remediate_path = output_dir.join(&remediate_filename);
        write_executable(&remediate_path, &remediate_content)?;

        Ok((audit_path, remediate_path))
    }

    /// Generate audit (check-only) script for a rule
    fn generate_audit_script(&self, rule: &MscpRule) -> Result<String> {
        let (check, expected) = extract_check_scripts(rule)?;
        let header = script_header("/bin/bash", &rule.id, &rule.title, &rule.discussion);
        let body = audit_script(&rule.id, &check, &expected);
        Ok(format!("{header}{body}"))
    }

    /// Generate remediate (fix) script for a rule
    fn generate_remediate_script(&self, rule: &MscpRule) -> Result<String> {
        let scripts = extract_rule_scripts(rule)?;
        let header = script_header("/bin/bash", &rule.id, &rule.title, &rule.discussion);
        let body = remediate_script(&rule.id, &scripts.check, &scripts.fix, &scripts.expected);
        Ok(format!("{header}{body}"))
    }

    /// Generate bundled script for a group of rules
    fn generate_bundled_audit_script(
        &self,
        category: &str,
        rules: &[&MscpRule],
        baseline_name: &str,
    ) -> Result<String> {
        let mut script = format!(
            "#!/bin/bash\n\
             # Bundled audit script for category: {category}\n\
             # Baseline: {baseline_name}\n\
             # Generated by contour mscp\n\
             # Contains {} rules\n\
             \n\
             TOTAL_RULES={}\n\
             PASSED=0\n\
             FAILED=0\n\n",
            rules.len(),
            rules.len()
        );

        // Add function for each rule
        for rule in rules {
            let (check, expected) = (
                rule.get_check_script().unwrap_or_default(),
                rule.get_expected_result()
                    .unwrap_or_else(|| "0".to_string()),
            );
            script.push_str(&bundled_check_fn(&rule.id, &check, &expected));
        }

        // Add main execution
        script.push_str("\n# Run all checks\n");
        script.push_str(&format!(
            "echo \"Running {} {} compliance checks...\"\n",
            rules.len(),
            category
        ));
        script.push_str("echo \"\"\n\n");

        for rule in rules {
            script.push_str(&format!("check_{}\n", rule.id.replace('-', "_")));
        }

        script.push_str(audit_summary());

        Ok(script)
    }

    /// Generate bundled remediate script for a group of rules
    fn generate_bundled_remediate_script(
        &self,
        category: &str,
        rules: &[&MscpRule],
        baseline_name: &str,
    ) -> Result<String> {
        let mut script = format!(
            "#!/bin/bash\n\
             # Bundled remediate script for category: {category}\n\
             # Baseline: {baseline_name}\n\
             # Generated by contour mscp\n\
             # Contains {} rules\n\
             # WARNING: This script will make changes to the system\n\
             \n\
             TOTAL_RULES={}\n\
             FIXED=0\n\
             ALREADY_COMPLIANT=0\n\
             FAILED_TO_FIX=0\n\n",
            rules.len(),
            rules.len()
        );

        // Add check and fix functions for each rule
        for rule in rules {
            let (check, fix, expected) = (
                rule.get_check_script().unwrap_or_default(),
                rule.get_fix_script().unwrap_or_default(),
                rule.get_expected_result()
                    .unwrap_or_else(|| "0".to_string()),
            );
            script.push_str(&bundled_remediate_fn(&rule.id, &check, &fix, &expected));
        }

        // Add main execution
        script.push_str("\n# Run all remediations\n");
        script.push_str(&format!(
            "echo \"Remediating {} {} compliance rules...\"\n",
            rules.len(),
            category
        ));
        script.push_str("echo \"\"\n\n");

        for rule in rules {
            script.push_str(&format!("remediate_{}\n", rule.id.replace('-', "_")));
        }

        script.push_str(remediate_summary());

        Ok(script)
    }

    /// Extract category from rule ID (e.g., "audit" from "`audit_acls_files_configure`")
    fn get_rule_category(rule_id: &str) -> String {
        // Extract prefix before first underscore or first two segments
        let parts: Vec<&str> = rule_id.split('_').collect();
        if parts.len() >= 2 {
            // For patterns like "system_settings_*", use first two parts
            if parts[0] == "system" && parts[1] == "settings" {
                "system_settings".to_string()
            } else {
                parts[0].to_string()
            }
        } else {
            parts[0].to_string()
        }
    }

    /// Generate scripts for all script rules in a baseline
    /// Returns Vec<(identifier, `audit_path`, `remediate_path`)>
    pub fn generate_for_baseline(
        &self,
        rules: &[MscpRule],
        baseline_name: &str,
        output_dir: &Path,
    ) -> Result<Vec<(String, PathBuf, PathBuf)>> {
        let mut generated = Vec::new();

        let script_rules = script_helpers::script_rules_for_baseline(rules, baseline_name);

        match self.options.mode {
            ScriptMode::Combined => {
                // Combined mode handled by ScriptTransformer (existing mSCP output)
                tracing::info!("Combined mode - handled by ScriptTransformer");
            }

            ScriptMode::Granular => {
                tracing::info!(
                    "Generating {} individual scripts for baseline '{}'",
                    script_rules.len(),
                    baseline_name
                );

                for rule in script_rules {
                    match self.generate_scripts_for_rule(rule, baseline_name, output_dir) {
                        Ok((audit_path, remediate_path)) => {
                            tracing::debug!(
                                "Generated scripts for rule {}: {} and {}",
                                rule.id,
                                audit_path.display(),
                                remediate_path.display()
                            );
                            generated.push((rule.id.clone(), audit_path, remediate_path));
                        }
                        Err(e) => {
                            tracing::warn!(
                                "Failed to generate scripts for rule {}: {}",
                                rule.id,
                                e
                            );
                        }
                    }
                }
            }

            ScriptMode::Bundled => {
                // Create output directory
                fs::create_dir_all(output_dir)?;

                // Group rules by category
                let mut categories: std::collections::HashMap<String, Vec<&MscpRule>> =
                    std::collections::HashMap::new();

                for rule in &script_rules {
                    let category = Self::get_rule_category(&rule.id);
                    categories.entry(category).or_default().push(rule);
                }

                tracing::info!(
                    "Generating {} bundled script categories for baseline '{}'",
                    categories.len(),
                    baseline_name
                );

                for (category, cat_rules) in categories {
                    tracing::info!("  Category '{}': {} rules", category, cat_rules.len());

                    // Generate bundled audit script
                    let audit_content =
                        self.generate_bundled_audit_script(&category, &cat_rules, baseline_name)?;
                    let audit_filename = format!("{baseline_name}_{category}_audit.sh");
                    let audit_path = output_dir.join(&audit_filename);
                    write_executable(&audit_path, &audit_content)?;

                    // Generate bundled remediate script
                    let remediate_content = self.generate_bundled_remediate_script(
                        &category,
                        &cat_rules,
                        baseline_name,
                    )?;
                    let remediate_filename = format!("{baseline_name}_{category}_remediate.sh");
                    let remediate_path = output_dir.join(&remediate_filename);
                    write_executable(&remediate_path, &remediate_content)?;

                    generated.push((category.clone(), audit_path, remediate_path));
                }
            }

            ScriptMode::Both => {
                // Generate both bundled and granular
                tracing::info!(
                    "Generating both bundled and granular scripts for baseline '{}'",
                    baseline_name
                );

                // First generate bundled
                let bundled_generator = RuleScriptGenerator::new(RuleScriptOptions {
                    mode: ScriptMode::Bundled,
                    ..self.options.clone()
                });
                let bundled =
                    bundled_generator.generate_for_baseline(rules, baseline_name, output_dir)?;
                generated.extend(bundled);

                // Then generate granular
                let granular_generator = RuleScriptGenerator::new(RuleScriptOptions {
                    mode: ScriptMode::Granular,
                    ..self.options.clone()
                });
                let granular =
                    granular_generator.generate_for_baseline(rules, baseline_name, output_dir)?;
                generated.extend(granular);
            }
        }

        tracing::info!(
            "Generated {} script pairs in: {}",
            generated.len(),
            output_dir.display()
        );

        Ok(generated)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transformers::script_helpers::create_test_rule;

    #[test]
    fn test_generate_audit_script() {
        let generator = RuleScriptGenerator::new(RuleScriptOptions::default());
        let rule = create_test_rule();

        let script = generator.generate_audit_script(&rule).unwrap();

        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("audit_acls_files_configure"));
        assert!(script.contains("/bin/ls -le /var/audit"));
        assert!(script.contains("Expected result: 0"));
    }

    #[test]
    fn test_generate_remediate_script() {
        let generator = RuleScriptGenerator::new(RuleScriptOptions::default());
        let rule = create_test_rule();

        let script = generator.generate_remediate_script(&rule).unwrap();

        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("audit_acls_files_configure"));
        assert!(script.contains("/bin/chmod -RN /var/audit"));
        assert!(script.contains("WARNING: This script will make changes to the system"));
    }
}
