//! Shared helpers for shell script generation across Fleet, Munki, and extract modes.
//!
//! Eliminates duplication of shell patterns (check, remediate, headers, summaries)
//! and common Rust utilities (rule metadata extraction, file permissions).

use crate::models::MscpRule;
use anyhow::{Context, Result};
use std::path::Path;

// ── Rule metadata extraction ────────────────────────────────────────

/// Extracted script components from an mSCP rule.
#[derive(Debug)]
pub struct RuleScripts {
    pub check: String,
    pub fix: String,
    pub expected: String,
}

/// Extract check, fix, and expected result from a rule.
/// Returns error if check or fix is missing.
pub fn extract_rule_scripts(rule: &MscpRule) -> Result<RuleScripts> {
    let check = rule.get_check_script().context("Missing check script")?;
    let fix = rule.get_fix_script().context("Missing fix script")?;
    let expected = rule
        .get_expected_result()
        .unwrap_or_else(|| "0".to_string());
    Ok(RuleScripts {
        check,
        fix,
        expected,
    })
}

/// Extract check and expected result only (no fix needed).
pub fn extract_check_scripts(rule: &MscpRule) -> Result<(String, String)> {
    let check = rule.get_check_script().context("Missing check script")?;
    let expected = rule
        .get_expected_result()
        .unwrap_or_else(|| "0".to_string());
    Ok((check, expected))
}

// ── Shell script building blocks ────────────────────────────────────

/// Generate a script header with shebang, rule metadata, and generator tag.
pub fn script_header(shell: &str, rule_id: &str, title: &str, description: &str) -> String {
    let desc_lines: String = description.lines().take(3).collect::<Vec<_>>().join("\n# ");
    format!(
        "#!{shell}\n\
         # Rule: {rule_id}\n\
         # Title: {title}\n\
         # Generated by contour mscp\n\
         #\n\
         # Description:\n\
         # {desc_lines}\n"
    )
}

/// Generate a standalone audit (check-only) script body.
///
/// Runs the check command and compares against the expected result.
pub fn audit_script(rule_id: &str, check: &str, expected: &str) -> String {
    format!(
        r#"
# Expected result: {expected}

# Run the check
CHECK_RESULT=$({check} 2>&1)
CHECK_EXIT=$?

echo "Result: $CHECK_RESULT"
echo "Exit code: $CHECK_EXIT"

# Compare result
if [[ "$CHECK_RESULT" == "{expected}" ]] && [[ $CHECK_EXIT -eq 0 ]]; then
    echo "✓ PASS: Rule {rule_id} is compliant"
    exit 0
else
    echo "✗ FAIL: Rule {rule_id} is non-compliant"
    echo "  Expected: {expected}"
    echo "  Got: $CHECK_RESULT"
    exit 1
fi
"#
    )
}

/// Generate a standalone remediate (check-fix-verify) script body.
///
/// Checks compliance first, applies fix if needed, then verifies.
pub fn remediate_script(_rule_id: &str, check: &str, fix: &str, expected: &str) -> String {
    format!(
        r#"#
# WARNING: This script will make changes to the system

# Check if already compliant
echo "Checking current compliance status..."
CHECK_RESULT_BEFORE=$({check} 2>&1)

if [[ "$CHECK_RESULT_BEFORE" == "{expected}" ]]; then
    echo "✓ Already compliant - no remediation needed"
    exit 0
fi

echo "✗ Non-compliant - applying remediation..."

# Apply the fix
{fix}

# Verify fix was successful
sleep 1
CHECK_RESULT_AFTER=$({check} 2>&1)

if [[ "$CHECK_RESULT_AFTER" == "{expected}" ]]; then
    echo "✓ Remediation successful"
    echo "  Before: $CHECK_RESULT_BEFORE"
    echo "  After: $CHECK_RESULT_AFTER"
    exit 0
else
    echo "✗ Remediation may not have been fully successful"
    echo "  Expected: {expected}"
    echo "  Got: $CHECK_RESULT_AFTER"
    exit 1
fi
"#
    )
}

/// Generate a per-rule check function for use in bundled audit scripts.
pub fn bundled_check_fn(rule_id: &str, check: &str, expected: &str) -> String {
    let fn_name = rule_id.replace('-', "_");
    format!(
        r#"
# Rule: {rule_id}
check_{fn_name}() {{
    local result=$({check} 2>&1)
    local expected="{expected}"

    if [[ "$result" == "$expected" ]]; then
        echo "✓ PASS: {rule_id}"
        ((PASSED++))
        return 0
    else
        echo "✗ FAIL: {rule_id}"
        echo "  Expected: $expected, Got: $result"
        ((FAILED++))
        return 1
    fi
}}

"#
    )
}

/// Generate a per-rule remediate function for use in bundled remediate scripts.
pub fn bundled_remediate_fn(rule_id: &str, check: &str, fix: &str, expected: &str) -> String {
    let fn_name = rule_id.replace('-', "_");
    format!(
        r#"
# Rule: {rule_id}
remediate_{fn_name}() {{
    local result_before=$({check} 2>&1)
    local expected="{expected}"

    if [[ "$result_before" == "$expected" ]]; then
        echo "✓ {rule_id} - Already compliant"
        ((ALREADY_COMPLIANT++))
        return 0
    fi

    echo "⚙ {rule_id} - Applying fix..."
    {fix}

    sleep 1
    local result_after=$({check} 2>&1)

    if [[ "$result_after" == "$expected" ]]; then
        echo "✓ {rule_id} - Fixed successfully"
        ((FIXED++))
        return 0
    else
        echo "✗ {rule_id} - Fix may not have been successful"
        ((FAILED_TO_FIX++))
        return 1
    fi
}}

"#
    )
}

/// Generate the summary/report block for a bundled audit script.
pub fn audit_summary() -> &'static str {
    r#"
# Summary
echo ""
echo "===================="
echo "Compliance Summary"
echo "===================="
echo "Total: $TOTAL_RULES"
echo "Passed: $PASSED"
echo "Failed: $FAILED"

if [[ $FAILED -eq 0 ]]; then
    echo ""
    echo "✓ All checks passed"
    exit 0
else
    echo ""
    echo "✗ $FAILED check(s) failed"
    exit 1
fi
"#
}

/// Generate the summary/report block for a bundled remediate script.
pub fn remediate_summary() -> &'static str {
    r#"
# Summary
echo ""
echo "===================="
echo "Remediation Summary"
echo "===================="
echo "Total: $TOTAL_RULES"
echo "Already Compliant: $ALREADY_COMPLIANT"
echo "Fixed: $FIXED"
echo "Failed to Fix: $FAILED_TO_FIX"

if [[ $FAILED_TO_FIX -eq 0 ]]; then
    echo ""
    echo "✓ All remediations successful"
    exit 0
else
    echo ""
    echo "✗ $FAILED_TO_FIX remediation(s) failed"
    exit 1
fi
"#
}

// ── File utilities ──────────────────────────────────────────────────

/// Write a script file and make it executable (0o755 on Unix).
pub fn write_executable(path: &Path, content: &str) -> Result<()> {
    std::fs::write(path, content)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(path)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(path, perms)?;
    };

    Ok(())
}

// ── Rule filtering ──────────────────────────────────────────────────

/// Filter rules that have script-based remediation for a given baseline.
pub fn script_rules_for_baseline<'a>(
    rules: &'a [MscpRule],
    baseline_name: &str,
) -> Vec<&'a MscpRule> {
    rules
        .iter()
        .filter(|r| {
            r.has_script_remediation() && r.has_executable_fix() && r.is_in_baseline(baseline_name)
        })
        .collect()
}

#[cfg(test)]
pub fn create_test_rule() -> MscpRule {
    use std::collections::HashMap;
    MscpRule {
        id: "audit_acls_files_configure".to_string(),
        title: "Configure Audit Log Files to Not Contain Access Control Lists".to_string(),
        discussion: "The audit log files _MUST_ not contain access control lists (ACLs)."
            .to_string(),
        check: Some(
            "/bin/ls -le /var/audit | /usr/bin/awk '{print $1}' | /usr/bin/grep -c \":\""
                .to_string(),
        ),
        result: {
            let mut map = yaml_serde::Mapping::new();
            map.insert(
                yaml_serde::Value::String("integer".to_string()),
                yaml_serde::Value::Number(0.into()),
            );
            Some(yaml_serde::Value::Mapping(map))
        },
        fix: Some("[source,bash]\n----\n/bin/chmod -RN /var/audit\n----".to_string()),
        references: HashMap::new(),
        macos: vec!["26.0".to_string()],
        tags: vec!["cis_lvl1".to_string()],
        severity: Some("medium".to_string()),
        mobileconfig: false,
        mobileconfig_info: None,
        odv: None,
    }
}
