use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Transformer for compliance scripts
#[derive(Debug)]
pub struct ScriptTransformer {
    output_base: PathBuf,
    jamf_mode: bool,
    fleet_output: bool,
}

impl ScriptTransformer {
    pub fn new<P: AsRef<Path>>(output_base: P, jamf_mode: bool, fleet_output: bool) -> Self {
        Self {
            output_base: output_base.as_ref().to_path_buf(),
            jamf_mode,
            fleet_output,
        }
    }

    /// Transform compliance script into separate audit and remediate scripts
    /// Returns (`audit_script_path`, `remediate_script_path`)
    pub fn transform(
        &self,
        baseline_name: &str,
        compliance_script_path: &Path,
    ) -> Result<(PathBuf, Option<PathBuf>)> {
        // Create output directory based on mode
        let scripts_dir = if self.jamf_mode {
            // Jamf mode: Direct structure {output}/{baseline_name}/scripts/
            self.output_base.join(baseline_name).join("scripts")
        } else if self.fleet_output {
            // Fleet mode: GitOps structure lib/mscp/{baseline_name}/scripts/
            self.output_base
                .join("lib")
                .join("mscp")
                .join(baseline_name)
                .join("scripts")
        } else {
            // Plain mode: mscp/{baseline_name}/scripts/
            self.output_base
                .join("mscp")
                .join(baseline_name)
                .join("scripts")
        };

        fs::create_dir_all(&scripts_dir)?;
        tracing::info!("Created scripts directory: {:?}", scripts_dir);

        // Read the compliance script
        let content = fs::read_to_string(compliance_script_path)
            .context("Failed to read compliance script")?;

        // For now, we'll create wrapper scripts that call the original with different flags
        // In the future, we could parse and split the script more intelligently

        let audit_script = self.create_audit_script(baseline_name, &content)?;
        let audit_path = scripts_dir.join(format!("{baseline_name}-audit.sh"));
        fs::write(&audit_path, audit_script)?;
        tracing::info!("Created audit script: {:?}", audit_path);

        // Optionally create remediation script
        let remediate_script = self.create_remediate_script(baseline_name, &content)?;
        let remediate_path = if remediate_script.is_empty() {
            None
        } else {
            let path = scripts_dir.join(format!("{baseline_name}-remediate.sh"));
            fs::write(&path, remediate_script)?;
            tracing::info!("Created remediate script: {:?}", path);
            Some(path)
        };

        Ok((audit_path, remediate_path))
    }

    /// Create an audit-only script
    fn create_audit_script(&self, baseline_name: &str, original_content: &str) -> Result<String> {
        // Check if the script supports --check flag
        if original_content.contains("--check") {
            Ok(format!(
                r#"#!/bin/bash
# Audit script for {baseline_name}
# Generated by contour mscp

# Run the compliance script in check mode
"${{BASH_SOURCE[0]%/*}}/{baseline_name}_compliance.sh" --check "$@"
"#
            ))
        } else {
            // If no --check flag, just copy the script as-is (assuming it's audit-only)
            Ok(original_content.to_string())
        }
    }

    /// Create a remediation script
    fn create_remediate_script(
        &self,
        baseline_name: &str,
        original_content: &str,
    ) -> Result<String> {
        // Check if the script supports --fix flag
        if original_content.contains("--fix") {
            Ok(format!(
                r#"#!/bin/bash
# Remediation script for {baseline_name}
# Generated by contour mscp
# WARNING: This script will make changes to the system

# Run the compliance script in fix mode
"${{BASH_SOURCE[0]%/*}}/{baseline_name}_compliance.sh" --fix "$@"
"#
            ))
        } else {
            // No remediation support
            Ok(String::new())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_script_transformer_creation() {
        let transformer = ScriptTransformer::new("/tmp/test", false, false);
        assert!(transformer.output_base.to_str().unwrap().contains("test"));
    }

    #[test]
    fn test_audit_script_generation() {
        let transformer = ScriptTransformer::new("/tmp/test", false, false);
        let original = r#"
#!/bin/bash
if [[ "$1" == "--check" ]]; then
    echo "Checking..."
fi
"#;
        let audit = transformer
            .create_audit_script("test_baseline", original)
            .unwrap();
        assert!(audit.contains("--check"));
    }
}
