use anyhow::{Context, Result};
use colored::Colorize;
use std::io::{self, Write};
use std::path::Path;

use crate::output::OutputMode;

const DEFAULT_CONFIG_NAME: &str = "profile.toml";

/// Prompt user for input with a default value
fn prompt(message: &str, default: Option<&str>) -> Result<String> {
    if let Some(def) = default {
        print!("{} [{}]: ", message, def.dimmed());
    } else {
        print!("{message}: ");
    }
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let input = input.trim().to_string();

    if input.is_empty() {
        Ok(default.unwrap_or("").to_string())
    } else {
        Ok(input)
    }
}

/// Prompt for yes/no with default
fn prompt_bool(message: &str, default: bool) -> Result<bool> {
    let default_str = if default { "Y/n" } else { "y/N" };
    print!("{message} [{default_str}]: ");
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let input = input.trim().to_lowercase();

    if input.is_empty() {
        Ok(default)
    } else {
        Ok(input == "y" || input == "yes")
    }
}

/// Generate config content
fn generate_config(domain: &str, name: &str, predictable_uuid: bool) -> String {
    format!(
        r#"# Profile Configuration
# Generated by: contour profile init

[organization]
domain = "{domain}"
name = "{name}"

[uuid]
predictable = {predictable_uuid}
uppercase = true

[output]
directory = "./profiles"

# Uncomment to enable Fleet GitOps integration:
# [fleet]
# gitops_root = "/path/to/fleet-gitops"
# target = "global"  # or "team"
# team_name = "Engineering"  # required if target = "team"
#
# [fleet.merge_map]
# default = "lib/macos/configuration-profiles"
"#,
    )
}

/// Handle `init` command
pub fn handle_init(
    output: Option<&str>,
    domain: Option<&str>,
    name: Option<&str>,
    force: bool,
    output_mode: OutputMode,
) -> Result<()> {
    let output_path = output.unwrap_or(DEFAULT_CONFIG_NAME);

    // Check if file exists
    if Path::new(output_path).exists() && !force {
        if output_mode == OutputMode::Json {
            let result = serde_json::json!({
                "success": false,
                "error": format!("Config file '{}' already exists. Use --force to overwrite.", output_path),
            });
            println!("{}", serde_json::to_string_pretty(&result)?);
            anyhow::bail!("Config already exists");
        }
        anyhow::bail!("Config file '{output_path}' already exists. Use --force to overwrite.");
    }

    // Get values - either from args or interactive prompts
    let final_domain: String;
    let final_name: String;
    let predictable_uuid: bool;

    // Non-interactive if both domain and name provided, or JSON mode
    let non_interactive = (domain.is_some() && name.is_some()) || output_mode == OutputMode::Json;

    if non_interactive {
        // Non-interactive mode - use args or defaults
        final_domain = domain
            .ok_or_else(|| anyhow::anyhow!("--domain required in non-interactive mode"))?
            .to_string();
        final_name = name
            .ok_or_else(|| anyhow::anyhow!("--name required in non-interactive mode"))?
            .to_string();
        predictable_uuid = true; // Default to true
    } else {
        // Interactive mode
        println!("{}", "Initializing Profile configuration...".cyan().bold());
        println!();

        final_domain = if let Some(d) = domain {
            d.to_string()
        } else {
            prompt("Organization domain (e.g., com.acme)", None)?
        };

        if final_domain.is_empty() {
            anyhow::bail!("Domain is required");
        }

        // Suggest name from domain (capitalize first letter)
        let suggested_name = final_domain
            .split('.')
            .next_back()
            .unwrap_or("myorg")
            .to_string();
        let suggested_name = suggested_name
            .chars()
            .next()
            .map(|c| c.to_uppercase().to_string() + &suggested_name[1..])
            .unwrap_or(suggested_name);

        final_name = if let Some(n) = name {
            n.to_string()
        } else {
            prompt("Organization name", Some(&suggested_name))?
        };

        predictable_uuid = prompt_bool("Use predictable UUIDs (recommended for GitOps)", true)?;
    }

    // Validate domain format
    if !final_domain.contains('.') && output_mode == OutputMode::Human {
        println!(
            "{} Domain '{}' doesn't look like a reverse domain (e.g., com.acme)",
            "Warning:".yellow(),
            final_domain
        );
    }

    // Generate and write config
    let config_content = generate_config(&final_domain, &final_name, predictable_uuid);

    std::fs::write(output_path, &config_content)
        .with_context(|| format!("Failed to write config to {output_path}"))?;

    if output_mode == OutputMode::Json {
        let result = serde_json::json!({
            "success": true,
            "path": output_path,
            "domain": final_domain,
            "name": final_name,
            "predictable_uuid": predictable_uuid,
        });
        println!("{}", serde_json::to_string_pretty(&result)?);
    } else {
        println!();
        println!("{} Created {}", "✓".green(), output_path.cyan());
        println!();
        println!("Configuration:");
        println!("  Domain: {}", final_domain.green());
        println!("  Name: {}", final_name.green());
        println!("  Predictable UUIDs: {predictable_uuid}");
        println!();
        println!("Next steps:");
        println!(
            "  {} - Normalize a profile",
            "contour profile normalize <profile.mobileconfig>".cyan()
        );
        println!(
            "  {} - Validate a profile",
            "contour profile validate <profile.mobileconfig>".cyan()
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_generate_config() {
        let config = generate_config("com.acme", "acme", true);
        assert!(config.contains("domain = \"com.acme\""));
        assert!(config.contains("name = \"acme\""));
        assert!(config.contains("predictable = true"));
    }

    #[test]
    fn test_generate_config_no_predictable() {
        let config = generate_config("com.test", "test", false);
        assert!(config.contains("predictable = false"));
    }

    #[test]
    fn test_init_creates_file() {
        let temp_dir = TempDir::new().unwrap();
        let config_path = temp_dir.path().join("profile.toml");

        let result = handle_init(
            Some(config_path.to_str().unwrap()),
            Some("com.test"),
            Some("test"),
            false,
            OutputMode::Json,
        );

        assert!(result.is_ok());
        assert!(config_path.exists());

        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(content.contains("com.test"));
    }

    #[test]
    fn test_init_refuses_overwrite_without_force() {
        let temp_dir = TempDir::new().unwrap();
        let config_path = temp_dir.path().join("profile.toml");

        // Create existing file
        std::fs::write(&config_path, "existing").unwrap();

        let result = handle_init(
            Some(config_path.to_str().unwrap()),
            Some("com.test"),
            Some("test"),
            false, // no force
            OutputMode::Json,
        );

        assert!(result.is_err());
    }

    #[test]
    fn test_init_overwrites_with_force() {
        let temp_dir = TempDir::new().unwrap();
        let config_path = temp_dir.path().join("profile.toml");

        // Create existing file
        std::fs::write(&config_path, "existing").unwrap();

        let result = handle_init(
            Some(config_path.to_str().unwrap()),
            Some("com.new"),
            Some("new"),
            true, // force
            OutputMode::Json,
        );

        assert!(result.is_ok());
        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(content.contains("com.new"));
    }
}
