//! `profile library new` — scaffold an external preset/recipe library.
//!
//! Creates the directory tree and writes a starter README, validate
//! workflow, and a copy of every embedded DDM preset + MDM recipe.
//! End users point contour at the resulting directory via
//! `--preset-path` / `--recipe-path` (or drop into
//! `~/.contour/{presets,recipes}/`).

use crate::ddm::presets;
use crate::output::OutputMode;
use crate::recipe;
use anyhow::{Context, Result};
use colored::Colorize;
use std::path::{Path, PathBuf};

const README_BODY: &str = r"# Contour preset & recipe library

Generated by `contour profile library new`. Drop one TOML file per
intent into `ddm/` (DDM bundles) or `recipes/` (MDM mobileconfig
recipes), then point contour at this directory:

```bash
# DDM
contour profile ddm compose \
    --preset-path ./ddm \
    --preset <name> \
    --org com.acme \
    -o ./out

# MDM
contour profile generate \
    --recipe-path ./recipes \
    --recipe <name> \
    --org com.acme \
    -o ./out
```

## Resolution order

contour looks up names in this order:

1. **Explicit `--preset-path` / `--recipe-path`** (file or directory)
2. **`~/.contour/presets/`** or **`~/.contour/recipes/`**
3. **Embedded built-ins** compiled into the contour binary

External entries win on collision. `--list-presets` and `--list-recipes`
flag shadowed names with `(overrides embedded)` so you can see what is
shadowing what.

## Authoring

Each `.toml` filename (without the extension) is the preset/recipe
name. The first comment block at the top of each file becomes the
listing description, so write a short summary on every file.

Every `.toml` ships with a sibling `<name>.meaning.md` — a markdown
sidecar for the deeper context that does not fit in a TOML header
(intent, platforms, Apple-side defaults, references). Edit the
sidecar when you change the TOML; reviewers read the markdown to
understand *why* a preset exists, not just *what* it sets.

The starter files copied into this library are exact replicas of the
embedded built-ins — modify them in place to override, or rename to
add new intents alongside.

## CI

`.github/workflows/validate.yml` runs `--list-presets` / `--list-recipes`
on every push and smoke-composes each entry with a synthetic `--org`,
catching malformed TOML before it reaches end users.
";

const VALIDATE_WORKFLOW: &str = r#"name: validate-library

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install contour
        run: |
          # Adjust to your preferred install path / version pin.
          curl -fsSL https://github.com/declarative-io/contour/releases/latest/download/contour-x86_64-unknown-linux-gnu.tar.gz \
            | tar xz -C /usr/local/bin

      - name: List DDM presets (asserts every TOML parses)
        if: hashFiles('ddm/*.toml') != ''
        run: |
          contour profile ddm compose \
            --preset-path ./ddm --list-presets --json \
          | tee ddm-presets.json
          test "$(jq 'length' ddm-presets.json)" -gt 0

      - name: Smoke-compose every DDM preset
        if: hashFiles('ddm/*.toml') != ''
        run: |
          set -euo pipefail
          mkdir -p .compose-smoke
          for name in $(jq -r '.[].name' ddm-presets.json); do
            echo "::group::compose $name"
            contour profile ddm compose \
              --preset-path ./ddm --preset "$name" \
              --org com.example.ci \
              -o ".compose-smoke/$name"
            echo "::endgroup::"
          done

      - name: List MDM recipes (asserts every TOML parses)
        if: hashFiles('recipes/*.toml') != ''
        run: |
          contour profile generate \
            --recipe-path ./recipes --list-recipes --json \
          | tee mdm-recipes.json
"#;

const GITIGNORE_BODY: &str = ".compose-smoke/\nddm-presets.json\nmdm-recipes.json\n";

/// Options for `library new`.
#[derive(Debug)]
pub struct LibraryNewOptions<'a> {
    pub path: &'a Path,
    pub include_presets: bool,
    pub include_recipes: bool,
    pub force: bool,
}

/// Scaffold a preset/recipe library at `opts.path`. Returns the list of
/// files written so the JSON emitter can advertise them.
pub fn handle_library_new(opts: LibraryNewOptions<'_>, output_mode: OutputMode) -> Result<()> {
    let root = opts.path;

    // Refuse to overwrite a non-empty directory unless --force.
    if root.exists() {
        if !root.is_dir() {
            anyhow::bail!("{} exists and is not a directory", root.display());
        }
        let has_entries = std::fs::read_dir(root)
            .with_context(|| format!("Failed to read {}", root.display()))?
            .next()
            .is_some();
        if has_entries && !opts.force {
            anyhow::bail!(
                "{} already exists and is not empty. Re-run with --force to overwrite.",
                root.display()
            );
        }
    }

    std::fs::create_dir_all(root)
        .with_context(|| format!("Failed to create {}", root.display()))?;

    let mut written: Vec<PathBuf> = Vec::new();

    // Top-level files.
    write_file(
        &root.join("README.md"),
        README_BODY.as_bytes(),
        &mut written,
    )?;
    write_file(
        &root.join(".gitignore"),
        GITIGNORE_BODY.as_bytes(),
        &mut written,
    )?;

    // CI workflow.
    let workflow_dir = root.join(".github/workflows");
    std::fs::create_dir_all(&workflow_dir)
        .with_context(|| format!("Failed to create {}", workflow_dir.display()))?;
    write_file(
        &workflow_dir.join("validate.yml"),
        VALIDATE_WORKFLOW.as_bytes(),
        &mut written,
    )?;

    // DDM presets — each TOML gets a sibling `.meaning.md` describing
    // intent in human-readable markdown.
    if opts.include_presets {
        let ddm_dir = root.join("ddm");
        std::fs::create_dir_all(&ddm_dir)
            .with_context(|| format!("Failed to create {}", ddm_dir.display()))?;
        for (name, desc, body) in presets::EMBEDDED {
            let toml_target = ddm_dir.join(format!("{name}.toml"));
            write_file(&toml_target, body.as_bytes(), &mut written)?;
            let meaning_target = ddm_dir.join(format!("{name}.meaning.md"));
            write_file(
                &meaning_target,
                meaning_md_for(name, desc, body, "DDM bundle").as_bytes(),
                &mut written,
            )?;
        }
    }

    // MDM recipes — same sibling `.meaning.md` pattern.
    if opts.include_recipes {
        let recipes_dir = root.join("recipes");
        std::fs::create_dir_all(&recipes_dir)
            .with_context(|| format!("Failed to create {}", recipes_dir.display()))?;
        for (name, body) in recipe::loader::EMBEDDED_RECIPES {
            let toml_target = recipes_dir.join(format!("{name}.toml"));
            write_file(&toml_target, body.as_bytes(), &mut written)?;
            let meaning_target = recipes_dir.join(format!("{name}.meaning.md"));
            write_file(
                &meaning_target,
                meaning_md_for(name, "", body, "MDM recipe").as_bytes(),
                &mut written,
            )?;
        }
    }

    match output_mode {
        OutputMode::Json => emit_json(root, &written)?,
        OutputMode::Human => emit_human(root, &written, &opts),
    }

    Ok(())
}

/// Build the `<name>.meaning.md` sibling for a preset or recipe.
///
/// Pulls the leading TOML comment block as the "Intent" body so the
/// authored context flows naturally into the markdown sidecar. The
/// rest is a fixed template the operator fills in.
fn meaning_md_for(name: &str, fallback_desc: &str, toml_body: &str, kind: &str) -> String {
    let intent = extract_leading_toml_comments(toml_body)
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| {
            if fallback_desc.is_empty() {
                format!("Describe what `{name}` does and why this library ships it.")
            } else {
                fallback_desc.to_string()
            }
        });

    format!(
        "# {name}\n\
        \n\
        {kind} sidecar — fill in the sections below to document what this\n\
        intent does, where it applies, and where the authoritative\n\
        spec lives. The listing description still comes from the\n\
        leading comment block of `{name}.toml`; this file is for the\n\
        deeper context that does not fit in a TOML header.\n\
        \n\
        ## Intent\n\
        \n\
        {intent}\n\
        \n\
        ## Platforms\n\
        \n\
        - [ ] macOS\n\
        - [ ] iOS / iPadOS\n\
        - [ ] tvOS\n\
        - [ ] visionOS\n\
        \n\
        ## Apple defaults\n\
        \n\
        Note any keys whose Apple-side default differs from this preset\n\
        — those are the ones that *actually* change behaviour when this\n\
        intent applies.\n\
        \n\
        ## References\n\
        \n\
        - Apple device-management spec: <https://developer.apple.com/documentation/devicemanagement>\n\
        - contour schema lookup: `contour profile info <payload_type> --full`\n\
        \n\
        ## Compose example\n\
        \n\
        ```bash\n\
        contour profile ddm compose \\\n    --preset-path ./ddm \\\n    --preset {name} \\\n    --org com.acme \\\n    -o ./out\n\
        ```\n",
    )
}

/// Best-effort extraction of the leading `# ...` comment block of a
/// TOML body. Returns the comment lines joined with newlines (`#`
/// stripped, blank lines dropped at the boundary).
fn extract_leading_toml_comments(toml_body: &str) -> Option<String> {
    let mut lines: Vec<String> = Vec::new();
    for line in toml_body.lines() {
        let trimmed = line.trim_start();
        if trimmed.is_empty() {
            if lines.is_empty() {
                continue;
            }
            break;
        }
        if let Some(rest) = trimmed.strip_prefix('#') {
            let cleaned = rest.trim_start_matches([' ', '#']).trim_end();
            lines.push(cleaned.to_string());
        } else {
            break;
        }
    }
    if lines.is_empty() {
        None
    } else {
        Some(lines.join("\n"))
    }
}

fn write_file(path: &Path, body: &[u8], written: &mut Vec<PathBuf>) -> Result<()> {
    std::fs::write(path, body).with_context(|| format!("Failed to write {}", path.display()))?;
    written.push(path.to_path_buf());
    Ok(())
}

fn emit_json(root: &Path, written: &[PathBuf]) -> Result<()> {
    let payload = serde_json::json!({
        "success": true,
        "root": root.display().to_string(),
        "files": written.iter().map(|p| p.display().to_string()).collect::<Vec<_>>(),
        "file_count": written.len(),
    });
    println!("{}", serde_json::to_string_pretty(&payload)?);
    Ok(())
}

fn emit_human(root: &Path, written: &[PathBuf], opts: &LibraryNewOptions<'_>) {
    println!(
        "{} Scaffolded preset library at {}",
        "✓".green(),
        root.display().to_string().bold()
    );
    println!("  {} files written", written.len());
    if opts.include_presets {
        println!(
            "  {} ddm/      ({} embedded preset(s))",
            "•".cyan(),
            presets::EMBEDDED.len()
        );
    }
    if opts.include_recipes {
        println!(
            "  {} recipes/  ({} embedded recipe(s))",
            "•".cyan(),
            recipe::loader::EMBEDDED_RECIPES.len()
        );
    }
    println!();
    println!("Next steps:");
    println!("  cd {}", root.display());
    println!("  contour profile ddm compose --preset-path ./ddm --list-presets");
    println!("  contour profile generate    --recipe-path ./recipes --list-recipes");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaffold_writes_expected_layout() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("contour-presets");
        handle_library_new(
            LibraryNewOptions {
                path: &root,
                include_presets: true,
                include_recipes: true,
                force: false,
            },
            OutputMode::Json,
        )
        .unwrap();

        assert!(root.join("README.md").exists());
        assert!(root.join(".gitignore").exists());
        assert!(root.join(".github/workflows/validate.yml").exists());

        // Every embedded preset / recipe should land in the right
        // subdir alongside its `.meaning.md` sidecar.
        for (name, _, _) in presets::EMBEDDED {
            assert!(
                root.join("ddm").join(format!("{name}.toml")).exists(),
                "missing ddm/{name}.toml"
            );
            assert!(
                root.join("ddm").join(format!("{name}.meaning.md")).exists(),
                "missing ddm/{name}.meaning.md"
            );
        }
        for (name, _) in recipe::loader::EMBEDDED_RECIPES {
            assert!(
                root.join("recipes").join(format!("{name}.toml")).exists(),
                "missing recipes/{name}.toml"
            );
            assert!(
                root.join("recipes")
                    .join(format!("{name}.meaning.md"))
                    .exists(),
                "missing recipes/{name}.meaning.md"
            );
        }
    }

    #[test]
    fn meaning_md_pulls_intent_from_leading_toml_comments() {
        let body = "# First line of intent.\n\
                    # Second line.\n\
                    \n\
                    intent_name = \"x\"\n";
        let md = meaning_md_for("x", "fallback", body, "DDM bundle");
        // The Intent section must include the comment lines, NOT the
        // fallback string when comments are present.
        assert!(
            md.contains("First line of intent."),
            "intent must come from leading TOML comments; got: {md}"
        );
        assert!(md.contains("Second line."));
        assert!(!md.contains("fallback"));
    }

    #[test]
    fn scaffold_refuses_non_empty_dir_without_force() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().to_path_buf();
        // tempdir is empty by default; drop a file to make it non-empty.
        std::fs::write(root.join("preexisting.txt"), "x").unwrap();

        let err = handle_library_new(
            LibraryNewOptions {
                path: &root,
                include_presets: true,
                include_recipes: true,
                force: false,
            },
            OutputMode::Json,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("already exists and is not empty"),
            "expected non-empty refusal, got: {err}"
        );
    }

    #[test]
    fn scaffold_force_overwrites_existing() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().to_path_buf();
        std::fs::write(root.join("preexisting.txt"), "x").unwrap();

        handle_library_new(
            LibraryNewOptions {
                path: &root,
                include_presets: false,
                include_recipes: false,
                force: true,
            },
            OutputMode::Json,
        )
        .unwrap();
        // README must land even though dir was non-empty.
        assert!(root.join("README.md").exists());
    }

    #[test]
    fn scaffold_omits_disabled_sections() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("only-presets");
        handle_library_new(
            LibraryNewOptions {
                path: &root,
                include_presets: true,
                include_recipes: false,
                force: false,
            },
            OutputMode::Json,
        )
        .unwrap();
        assert!(root.join("ddm").is_dir());
        assert!(
            !root.join("recipes").exists(),
            "recipes dir must be skipped"
        );
    }
}
