// Baseline reference models - public API
#![allow(dead_code, reason = "module under development")]

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// TOML-based baseline manifest
/// This format clearly distinguishes mscp metadata from Fleet YAML configs
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaselineReference {
    pub baseline: BaselineMetadata,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<SourceInfo>,
    #[serde(default)]
    pub profiles: Vec<ProfileEntry>,
    #[serde(default)]
    pub scripts: Vec<ScriptEntry>,
    #[serde(default)]
    pub excluded_profiles: Vec<ExcludedProfile>,
}

/// Baseline metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaselineMetadata {
    pub name: String,
    pub platform: String,
    pub generated_at: DateTime<Utc>,
}

/// Source information from mSCP
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceInfo {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mscp_repo: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mscp_commit: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mscp_version: Option<String>,
}

/// Configuration profile entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProfileEntry {
    pub path: String,
    pub labels_include_all: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labels_include_any: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labels_exclude_any: Option<Vec<String>>,
}

/// Script entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptEntry {
    pub path: String,
    pub labels_include_all: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labels_include_any: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labels_exclude_any: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub script_type: Option<String>,
}

/// Excluded profile (filtered by Fleet/Jamf constraints)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExcludedProfile {
    pub filename: String,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fleet_alternative: Option<String>,
}

impl BaselineReference {
    /// Create a new baseline reference
    pub fn new(baseline_name: String, platform: String) -> Self {
        Self {
            baseline: BaselineMetadata {
                name: baseline_name,
                platform,
                generated_at: Utc::now(),
            },
            source: None,
            profiles: Vec::new(),
            scripts: Vec::new(),
            excluded_profiles: Vec::new(),
        }
    }

    /// Add source information
    pub fn with_source(
        mut self,
        mscp_repo: Option<String>,
        mscp_commit: Option<String>,
        mscp_version: Option<String>,
    ) -> Self {
        self.source = Some(SourceInfo {
            mscp_repo,
            mscp_commit,
            mscp_version,
        });
        self
    }

    /// Add a profile entry
    pub fn add_profile(&mut self, path: String, labels_include_all: Vec<String>) {
        self.profiles.push(ProfileEntry {
            path,
            labels_include_all,
            labels_include_any: None,
            labels_exclude_any: None,
        });
    }

    /// Add a script entry
    pub fn add_script(
        &mut self,
        path: String,
        labels_include_all: Vec<String>,
        script_type: Option<String>,
    ) {
        self.scripts.push(ScriptEntry {
            path,
            labels_include_all,
            labels_include_any: None,
            labels_exclude_any: None,
            script_type,
        });
    }

    /// Add an excluded profile
    pub fn add_excluded_profile(
        &mut self,
        filename: String,
        reason: String,
        fleet_alternative: Option<String>,
    ) {
        self.excluded_profiles.push(ExcludedProfile {
            filename,
            reason,
            fleet_alternative,
        });
    }

    /// Generate TOML string with header comments
    pub fn to_toml_string(&self) -> anyhow::Result<String> {
        let header = format!(
            r"# mscp Baseline Manifest
# Generated by contour mscp - DO NOT DEPLOY TO FLEET
#
# This file documents all profiles and scripts included in the {} baseline.
# This is NOT a Fleet configuration file - it uses TOML format to clearly
# distinguish mscp metadata from deployable Fleet YAML files.
#
# To use this baseline in Fleet teams:
#   1. See fleets/examples/mscp-{}-example.yml for usage patterns
#   2. Reference individual .mobileconfig and .sh files in your team YAML
#   3. Fleet does not support including TOML manifests
#
# For more information:
#   https://github.com/headmin/contour

",
            self.baseline.name, self.baseline.name
        );

        let toml_content = toml::to_string_pretty(self)?;
        Ok(format!("{header}{toml_content}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_baseline_reference_creation() {
        let baseline = BaselineReference::new("cis_lvl1".to_string(), "macos".to_string());
        assert_eq!(baseline.baseline.name, "cis_lvl1");
        assert_eq!(baseline.baseline.platform, "macos");
        assert!(baseline.profiles.is_empty());
        assert!(baseline.scripts.is_empty());
    }

    #[test]
    fn test_add_profile() {
        let mut baseline = BaselineReference::new("test".to_string(), "macos".to_string());
        baseline.add_profile(
            "./profiles/test.mobileconfig".to_string(),
            vec!["mscp-test".to_string()],
        );

        assert_eq!(baseline.profiles.len(), 1);
        assert_eq!(baseline.profiles[0].path, "./profiles/test.mobileconfig");
        assert_eq!(baseline.profiles[0].labels_include_all, vec!["mscp-test"]);
    }

    #[test]
    fn test_toml_serialization() {
        let mut baseline = BaselineReference::new("test".to_string(), "macos".to_string());
        baseline.add_profile(
            "./profiles/test.mobileconfig".to_string(),
            vec!["mscp-test".to_string()],
        );

        let toml_string = baseline.to_toml_string();
        assert!(toml_string.is_ok());

        let toml = toml_string.unwrap();
        assert!(toml.contains("# mscp Baseline Manifest"));
        assert!(toml.contains("[baseline]"));
        assert!(toml.contains("[[profiles]]"));
    }
}
