//! Generate Santa prerequisite profiles for MDM deployment.
//!
//! Creates the five profiles required for Santa to function properly:
//! - System Extension Policy (allow Santa's endpoint security extension)
//! - Service Management (managed login items)
//! - TCC/PPPC (Full Disk Access for Santa components)
//! - Notification Settings (enable Santa notifications)
//! - Santa Configuration (basic client settings)

use crate::output::{OutputMode, print_info, print_kv, print_success};
use anyhow::{Context, Result};
use contour_profiles::ProfileBuilder;
use plist::{Dictionary, Value};
use std::path::Path;

/// Santa's Team ID (North Pole Security)
const SANTA_TEAM_ID: &str = "ZMCG7MLDV9";

/// Santa bundle identifiers
const SANTA_APP_BUNDLE_ID: &str = "com.northpolesec.santa";
const SANTA_DAEMON_BUNDLE_ID: &str = "com.northpolesec.santa.daemon";
const SANTA_BUNDLE_SERVICE_ID: &str = "com.northpolesec.santa.bundleservice";

/// Profile types generated by prep
#[derive(Debug, Clone, Copy)]
pub enum PrepProfile {
    SystemExtension,
    ServiceManagement,
    Tcc,
    Notifications,
    Config,
}

impl PrepProfile {
    fn name(&self) -> &'static str {
        match self {
            PrepProfile::SystemExtension => "system-extension",
            PrepProfile::ServiceManagement => "service-management",
            PrepProfile::Tcc => "tcc",
            PrepProfile::Notifications => "notifications",
            PrepProfile::Config => "config",
        }
    }

    fn display_name(&self) -> &'static str {
        match self {
            PrepProfile::SystemExtension => "Santa System Extension Policy",
            PrepProfile::ServiceManagement => "Santa Service Management",
            PrepProfile::Tcc => "Santa Privacy Preferences",
            PrepProfile::Notifications => "Santa Notifications",
            PrepProfile::Config => "Santa Configuration",
        }
    }

    fn payload_type(&self) -> &'static str {
        match self {
            PrepProfile::SystemExtension => "com.apple.system-extension-policy",
            PrepProfile::ServiceManagement => "com.apple.servicemanagement",
            PrepProfile::Tcc => "com.apple.TCC.configuration-profile-policy",
            PrepProfile::Notifications => "com.apple.notificationsettings",
            PrepProfile::Config => "com.northpolesec.santa",
        }
    }
}

/// Run the prep command.
pub fn run(output_dir: &Path, org: &str, dry_run: bool, mode: OutputMode) -> Result<()> {
    if mode == OutputMode::Human {
        print_info("Generating Santa prerequisite profiles...");
        print_kv("Organization", org);
        print_kv("Output directory", &output_dir.display().to_string());
    }

    // Create output directory if it doesn't exist
    if !dry_run && !output_dir.exists() {
        std::fs::create_dir_all(output_dir).with_context(|| {
            format!(
                "Failed to create output directory: {}",
                output_dir.display()
            )
        })?;
    }

    let profiles = [
        PrepProfile::SystemExtension,
        PrepProfile::ServiceManagement,
        PrepProfile::Tcc,
        PrepProfile::Notifications,
        PrepProfile::Config,
    ];

    for profile_type in &profiles {
        let filename = format!("santa-{}.mobileconfig", profile_type.name());
        let output_path = output_dir.join(&filename);

        if dry_run {
            if mode == OutputMode::Human {
                print_kv("Would create", &output_path.display().to_string());
            }
        } else {
            let content = generate_profile(*profile_type, org)?;
            std::fs::write(&output_path, content)
                .with_context(|| format!("Failed to write {}", output_path.display()))?;

            if mode == OutputMode::Human {
                print_kv("Created", &output_path.display().to_string());
            }
        }
    }

    if mode == OutputMode::Human {
        println!();
        if dry_run {
            print_info("Dry run - no files written");
        } else {
            print_success("Santa prerequisite profiles generated successfully!");
            println!();
            print_info("Deploy these profiles via MDM before deploying Santa rules.");
            print_info("Recommended deployment order:");
            println!("  1. santa-system-extension.mobileconfig");
            println!("  2. santa-service-management.mobileconfig");
            println!("  3. santa-tcc.mobileconfig");
            println!("  4. santa-notifications.mobileconfig");
            println!("  5. santa-config.mobileconfig");
            println!("  6. Santa rules profile(s)");
        }
    }

    Ok(())
}

/// Generate a profile of the specified type using the shared ProfileBuilder.
fn generate_profile(profile_type: PrepProfile, org: &str) -> Result<Vec<u8>> {
    let profile_id = format!("{}.santa.prep.{}", org, profile_type.name());

    let payload_content = match profile_type {
        PrepProfile::SystemExtension => build_system_extension_payload(),
        PrepProfile::ServiceManagement => build_service_management_payload(),
        PrepProfile::Tcc => build_tcc_payload(),
        PrepProfile::Notifications => build_notifications_payload(),
        PrepProfile::Config => build_config_payload(),
    };

    let description = match profile_type {
        PrepProfile::Config => "Santa client configuration".to_string(),
        _ => format!("Santa {} configuration", profile_type.name()),
    };

    ProfileBuilder::new(org, &profile_id)
        .display_name(profile_type.display_name())
        .description(&description)
        .removal_disallowed(true)
        .build(profile_type.payload_type(), payload_content)
}

/// Build System Extension Policy payload.
fn build_system_extension_payload() -> Dictionary {
    let mut payload = Dictionary::new();

    // AllowedSystemExtensionTypes
    let mut allowed_types = Dictionary::new();
    allowed_types.insert(
        SANTA_TEAM_ID.to_string(),
        Value::Array(vec![Value::String("EndpointSecurityExtension".to_string())]),
    );
    payload.insert(
        "AllowedSystemExtensionTypes".to_string(),
        Value::Dictionary(allowed_types),
    );

    payload.insert("AllowUserOverrides".to_string(), Value::Boolean(true));

    // NonRemovableFromUISystemExtensions (prevent user from removing)
    let mut non_removable = Dictionary::new();
    non_removable.insert(
        SANTA_TEAM_ID.to_string(),
        Value::Array(vec![Value::String(SANTA_DAEMON_BUNDLE_ID.to_string())]),
    );
    payload.insert(
        "NonRemovableFromUISystemExtensions".to_string(),
        Value::Dictionary(non_removable),
    );

    // AllowedSystemExtensions
    let mut allowed_extensions = Dictionary::new();
    allowed_extensions.insert(
        SANTA_TEAM_ID.to_string(),
        Value::Array(vec![Value::String(SANTA_DAEMON_BUNDLE_ID.to_string())]),
    );
    payload.insert(
        "AllowedSystemExtensions".to_string(),
        Value::Dictionary(allowed_extensions),
    );

    payload
}

/// Build Service Management (Managed Login Items) payload.
fn build_service_management_payload() -> Dictionary {
    let rule =
        contour_profiles::build_service_management_rule(SANTA_TEAM_ID, SANTA_DAEMON_BUNDLE_ID);

    let mut payload = Dictionary::new();
    payload.insert(
        "Rules".to_string(),
        Value::Array(vec![Value::Dictionary(rule)]),
    );

    payload
}

/// Build TCC (Privacy Preferences Policy Control) payload.
fn build_tcc_payload() -> Dictionary {
    let mut payload = Dictionary::new();

    // Helper to create a TCC entry with Santa's code requirement
    let santa_tcc_entry = |bundle_id: &str| {
        let code_req = format!(
            r#"identifier "{}" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = {}"#,
            bundle_id, SANTA_TEAM_ID
        );
        contour_profiles::build_tcc_entry(bundle_id, &code_req, true)
    };

    // SystemPolicyAllFiles (Full Disk Access) for all Santa components
    let fda_entries = Value::Array(vec![
        santa_tcc_entry(SANTA_DAEMON_BUNDLE_ID),
        santa_tcc_entry(SANTA_BUNDLE_SERVICE_ID),
        santa_tcc_entry(SANTA_APP_BUNDLE_ID),
    ]);

    let mut services = Dictionary::new();
    services.insert("SystemPolicyAllFiles".to_string(), fda_entries);

    payload.insert("Services".to_string(), Value::Dictionary(services));

    payload
}

/// Build Notification Settings payload.
fn build_notifications_payload() -> Dictionary {
    let notification = contour_profiles::build_notification_entry(SANTA_APP_BUNDLE_ID);

    let mut payload = Dictionary::new();
    payload.insert(
        "NotificationSettings".to_string(),
        Value::Array(vec![Value::Dictionary(notification)]),
    );

    payload
}

/// Build Santa Configuration payload.
/// Provides basic defaults for Santa client operation.
fn build_config_payload() -> Dictionary {
    let mut payload = Dictionary::new();

    // ClientMode: 1 = Monitor (default, safe starting point)
    payload.insert("ClientMode".to_string(), Value::Integer(1.into()));

    // EnableSilentMode: false - show notifications to users
    payload.insert("EnableSilentMode".to_string(), Value::Boolean(false));

    // EnableBadSignatureProtection: block poorly signed binaries even in monitor mode
    payload.insert(
        "EnableBadSignatureProtection".to_string(),
        Value::Boolean(true),
    );

    // EventLogType: filelog - log events to file
    payload.insert(
        "EventLogType".to_string(),
        Value::String("filelog".to_string()),
    );

    payload
}

#[cfg(test)]
mod tests {
    use super::*;
    use contour_profiles::deterministic_uuid;

    #[test]
    fn test_deterministic_uuid() {
        let uuid1 = deterministic_uuid("com.example.santa.prep.system-extension");
        let uuid2 = deterministic_uuid("com.example.santa.prep.system-extension");
        assert_eq!(uuid1, uuid2);

        let uuid3 = deterministic_uuid("com.example.santa.prep.tcc");
        assert_ne!(uuid1, uuid3);
    }

    #[test]
    fn test_generate_system_extension_profile() {
        let content = generate_profile(PrepProfile::SystemExtension, "com.example").unwrap();
        let xml = String::from_utf8(content).unwrap();

        assert!(xml.contains("com.apple.system-extension-policy"));
        assert!(xml.contains(SANTA_TEAM_ID));
        assert!(xml.contains(SANTA_DAEMON_BUNDLE_ID));
        assert!(xml.contains("com.example.santa.prep.system-extension"));
    }

    #[test]
    fn test_generate_tcc_profile() {
        let content = generate_profile(PrepProfile::Tcc, "com.example").unwrap();
        let xml = String::from_utf8(content).unwrap();

        assert!(xml.contains("com.apple.TCC.configuration-profile-policy"));
        assert!(xml.contains("SystemPolicyAllFiles"));
        assert!(xml.contains(SANTA_APP_BUNDLE_ID));
        assert!(xml.contains(SANTA_DAEMON_BUNDLE_ID));
        assert!(xml.contains(SANTA_BUNDLE_SERVICE_ID));
    }

    #[test]
    fn test_generate_config_profile() {
        let content = generate_profile(PrepProfile::Config, "com.example").unwrap();
        let xml = String::from_utf8(content).unwrap();

        assert!(xml.contains("com.northpolesec.santa"));
        assert!(xml.contains("ClientMode"));
        assert!(xml.contains("EnableSilentMode"));
        assert!(xml.contains("EnableBadSignatureProtection"));
        assert!(xml.contains("com.example.santa.prep.config"));
    }

    #[test]
    fn test_profile_key_ordering() {
        // Verify PayloadContent appears before final metadata keys
        let content = generate_profile(PrepProfile::SystemExtension, "com.example").unwrap();
        let xml = String::from_utf8(content).unwrap();

        let payload_content_pos = xml.find("<key>PayloadContent</key>").unwrap();
        let payload_uuid_pos = xml.find("<key>PayloadUUID</key>").unwrap();
        let payload_identifier_pos = xml.find("<key>PayloadIdentifier</key>").unwrap();

        // PayloadContent should appear before PayloadUUID and PayloadIdentifier in outer profile
        assert!(payload_content_pos < payload_uuid_pos);
        assert!(payload_content_pos < payload_identifier_pos);
    }
}
