//! Bootstrap a `name.toml` naming map from a profile set.
//!
//! [`scan`] collects every app bundle id present — using the *same* extraction
//! [`classify`](super::classify_profile) uses — plus any payload types the map
//! doesn't cover. [`emit_name_toml`] renders a full, runnable schema scaffold
//! (formats + scope + kinds + subjects + apps) where newly-discovered bundle ids
//! get a best-guess friendly name for the operator to review. Closes the loop:
//! no bundle id silently falls back to its raw id.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use super::map::NamingMap;
use crate::profile::ConfigurationProfile;

/// What a scan found that the current map does not yet cover.
#[derive(Debug)]
pub struct ScanReport {
    /// App bundle ids present in the profiles but absent from `map.apps`.
    pub new_bundle_ids: BTreeSet<String>,
    /// Payload types seen but absent from `map.kinds`.
    pub new_payload_types: BTreeSet<String>,
    /// Number of profiles scanned.
    pub profiles_scanned: usize,
}

/// Scan profiles for app bundle ids and payload types not covered by `map`.
pub fn scan(profiles: &[ConfigurationProfile], map: &NamingMap) -> ScanReport {
    let mut new_bundle_ids = BTreeSet::new();
    let mut new_payload_types = BTreeSet::new();
    for profile in profiles {
        for payload in &profile.payload_content {
            if !map.kinds.contains_key(&payload.payload_type) {
                new_payload_types.insert(payload.payload_type.clone());
            }
            // Only payloads classify treats as app-config can yield a bundle id.
            let is_app_payload = map
                .subjects
                .get(&payload.payload_type)
                .is_some_and(|r| r.app_name);
            if is_app_payload {
                if let Some(id) = super::app_bundle_id(payload) {
                    if !map.apps.contains_key(&id) {
                        new_bundle_ids.insert(id);
                    }
                }
            }
        }
    }
    ScanReport {
        new_bundle_ids,
        new_payload_types,
        profiles_scanned: profiles.len(),
    }
}

/// A best-guess friendly name from a bundle id: the last non-generic dotted
/// segment, capitalized (camel-case kept). Always a starting point to review,
/// never authoritative — e.g. `com.spotify.client → Spotify`,
/// `com.paloaltonetworks.GlobalProtect.client → GlobalProtect`.
pub fn guess_app_name(bundle_id: &str) -> String {
    const GENERIC_TAILS: &[&str] = &[
        "client", "app", "agent", "gui", "service", "svc", "svcapp", "desktop", "mac", "macos",
        "helper", "ui", "banner", "notifier", "xos", "osx",
    ];
    let parts: Vec<&str> = bundle_id.split('.').filter(|s| !s.is_empty()).collect();
    if parts.is_empty() {
        return bundle_id.to_string();
    }
    let mut i = parts.len();
    while i > 1 && GENERIC_TAILS.contains(&parts[i - 1].to_ascii_lowercase().as_str()) {
        i -= 1;
    }
    capitalize(parts[i - 1])
}

/// Capitalize the first letter, keeping any existing internal capitals
/// (so `GlobalProtect` stays, `spotify` → `Spotify`).
fn capitalize(s: &str) -> String {
    if s.chars().any(char::is_uppercase) {
        return s.to_string();
    }
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// Render a full `name.toml` scaffold from `map`, appending the scanned
/// `report.new_bundle_ids` to `[apps]` with best-guess values for review.
pub fn emit_name_toml(report: &ScanReport, map: &NamingMap) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# name.toml — generated by `contour profile classify --emit-map`."
    );
    let _ = writeln!(
        s,
        "# Scanned {} profile(s). {} new bundle id(s) need a friendly name —",
        report.profiles_scanned,
        report.new_bundle_ids.len()
    );
    let _ = writeln!(
        s,
        "# review the best-guess values marked `# review` in [apps] below."
    );
    if !report.new_payload_types.is_empty() {
        let types: Vec<&str> = report
            .new_payload_types
            .iter()
            .map(String::as_str)
            .collect();
        let _ = writeln!(s, "# Unmapped payload types seen: {}", types.join(", "));
    }
    let _ = writeln!(s);

    let _ = writeln!(s, "system_format = {:?}", map.system_format);
    let _ = writeln!(s, "app_format = {:?}", map.app_format);
    let _ = writeln!(s, "multi_kind_join = {:?}", map.multi_kind_join);
    let _ = writeln!(s);

    let _ = writeln!(s, "[scope]");
    let _ = writeln!(s, "system_label = {:?}", map.scope.system_label);
    let _ = writeln!(s, "app_label = {:?}", map.scope.app_label);
    let _ = writeln!(s, "user_label = {:?}", map.scope.user_label);
    let apt: Vec<String> = map
        .scope
        .app_payload_types
        .iter()
        .map(|t| format!("{t:?}"))
        .collect();
    let _ = writeln!(s, "app_payload_types = [{}]", apt.join(", "));
    let _ = writeln!(s);

    let _ = writeln!(s, "[kinds]");
    for (k, v) in &map.kinds {
        let _ = writeln!(s, "{k:?} = {v:?}");
    }
    let _ = writeln!(s);

    for (k, rule) in &map.subjects {
        let _ = writeln!(s, "[subjects.{k:?}]");
        if let Some(field) = &rule.field {
            let _ = writeln!(s, "field = {field:?}");
        }
        if rule.cert_subject_cn {
            let _ = writeln!(s, "cert_subject_cn = true");
        }
        if rule.app_name {
            let _ = writeln!(s, "app_name = true");
        }
        if let Some(fe) = &rule.from_existing {
            let _ = writeln!(s, "[subjects.{k:?}.from_existing]");
            let sl: Vec<String> = fe.strip_leading.iter().map(|x| format!("{x:?}")).collect();
            let _ = writeln!(s, "strip_leading = [{}]", sl.join(", "));
        }
        let _ = writeln!(s);
    }

    let _ = writeln!(s, "[apps]");
    if !map.apps.is_empty() {
        let _ = writeln!(s, "# --- existing mappings ---");
        for (k, v) in &map.apps {
            let _ = writeln!(s, "{k:?} = {v:?}");
        }
    }
    // Discovered ids the map doesn't already cover (skip any overlap so the
    // emitted TOML never has a duplicate key).
    let discovered: Vec<&String> = report
        .new_bundle_ids
        .iter()
        .filter(|id| !map.apps.contains_key(*id))
        .collect();
    if !discovered.is_empty() {
        let _ = writeln!(s, "# --- discovered (best-guess — review) ---");
        for id in discovered {
            let _ = writeln!(s, "{:?} = {:?} # review", id, guess_app_name(id));
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn guess_strips_generic_tails_and_capitalizes() {
        assert_eq!(guess_app_name("com.spotify.client"), "Spotify");
        assert_eq!(
            guess_app_name("com.paloaltonetworks.GlobalProtect.client"),
            "GlobalProtect"
        );
        assert_eq!(guess_app_name("com.google.Chrome"), "Chrome");
        assert_eq!(guess_app_name("org.mozilla.firefox"), "Firefox");
    }

    #[test]
    fn emitted_scaffold_parses_back_as_a_map() {
        let map = NamingMap::embedded().unwrap();
        let report = ScanReport {
            new_bundle_ids: ["com.acme.customtool.client".to_string()]
                .into_iter()
                .collect(),
            new_payload_types: BTreeSet::new(),
            profiles_scanned: 1,
        };
        let toml = emit_name_toml(&report, &map);
        let reparsed = NamingMap::from_toml(&toml).expect("emitted TOML round-trips");
        assert_eq!(reparsed.system_format, map.system_format);
        // The discovered id is present with its best-guess name.
        assert_eq!(
            reparsed
                .apps
                .get("com.acme.customtool.client")
                .map(String::as_str),
            Some("Customtool")
        );
    }
}
