use std::fmt;

/// Named Fleet GitOps layout versions.
///
/// Add new variants here when Fleet changes its directory conventions.
/// The CLI exposes these as `--layout <name>` values.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum FleetLayoutVersion {
    /// Fleet v4.83+ (current recommended, April 2026+)
    #[default]
    V4_83,
    /// Fleet v4.82 layout
    V4_82,
    /// Legacy layout (pre-v4.82)
    Legacy,
}

impl FleetLayoutVersion {
    /// All known layout versions, newest first.
    pub fn all() -> &'static [Self] {
        &[Self::V4_83, Self::V4_82, Self::Legacy]
    }

    /// Resolve a layout version from a CLI string.
    ///
    /// Accepts: "v4.83", "current", "latest", "v4.82", "legacy", etc.
    pub fn from_name(name: &str) -> Option<Self> {
        match name.to_lowercase().as_str() {
            "v4.83" | "v4_83" | "current" | "latest" => Some(Self::V4_83),
            "v4.82" | "v4_82" => Some(Self::V4_82),
            "legacy" | "v4.81" | "v4_81" | "pre-v4.82" => Some(Self::Legacy),
            _ => None,
        }
    }

    /// Build the corresponding layout.
    pub fn layout(self) -> FleetLayout {
        match self {
            Self::V4_83 => FleetLayout::v4_83(),
            Self::V4_82 => FleetLayout::v4_82(),
            Self::Legacy => FleetLayout::legacy(),
        }
    }

    /// Human-readable name for help text.
    pub fn display_name(self) -> &'static str {
        match self {
            Self::V4_83 => "v4.83+ (current)",
            Self::V4_82 => "v4.82",
            Self::Legacy => "legacy (pre-v4.82)",
        }
    }
}

impl fmt::Display for FleetLayoutVersion {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.display_name())
    }
}

/// Centralized Fleet GitOps directory layout conventions.
///
/// All path segments and file names for Fleet GitOps output are defined here.
/// When Fleet changes its conventions, add a new [`FleetLayoutVersion`] variant
/// and a constructor here — all generators pick it up automatically.
///
/// The v4.83 layout is the definitive structure generated by `fleetctl new`.
#[derive(Debug, Clone)]
pub struct FleetLayout {
    /// Which version this layout represents
    pub version: FleetLayoutVersion,
    /// Top-level directory for platform resources
    pub platforms_dir: &'static str,
    /// Top-level directory for fleet YAML files
    pub fleets_dir: &'static str,
    /// Top-level directory for labels
    pub labels_dir: &'static str,
    /// Filename for unassigned hosts
    pub unassigned_filename: &'static str,
    /// Display name for unassigned hosts in YAML
    pub unassigned_name: &'static str,
    /// YAML key for fleet-level settings
    pub settings_key: &'static str,
    /// Shared agent options file location (referenced from fleet YAML)
    pub agent_options_path: &'static str,

    // ── macOS paths ──────────────────────────────────────────
    /// macOS configuration profiles (.mobileconfig)
    pub macos_profiles_subdir: &'static str,
    /// macOS declaration profiles (.json DDM)
    pub macos_declarations_subdir: &'static str,
    /// macOS MDM commands
    pub macos_commands_subdir: &'static str,
    /// macOS enrollment profiles (DEP)
    pub macos_enrollment_subdir: &'static str,
    /// macOS scripts
    pub macos_scripts_subdir: &'static str,
    /// macOS policies
    pub macos_policies_subdir: &'static str,
    /// macOS reports
    pub macos_reports_subdir: &'static str,
    /// macOS software
    pub macos_software_subdir: &'static str,

    // ── iOS paths ────────────────────────────────────────────
    /// iOS configuration profiles
    pub ios_profiles_subdir: &'static str,
    /// iOS declaration profiles
    pub ios_declarations_subdir: &'static str,

    // ── iPadOS paths ─────────────────────────────────────────
    /// iPadOS configuration profiles
    pub ipados_profiles_subdir: &'static str,
    /// iPadOS declaration profiles
    pub ipados_declarations_subdir: &'static str,

    // ── Windows paths ────────────────────────────────────────
    /// Windows configuration profiles (.xml)
    pub windows_profiles_subdir: &'static str,
    /// Windows scripts
    pub windows_scripts_subdir: &'static str,
    /// Windows policies
    pub windows_policies_subdir: &'static str,
    /// Windows reports
    pub windows_reports_subdir: &'static str,
    /// Windows software
    pub windows_software_subdir: &'static str,

    // ── Linux paths ──────────────────────────────────────────
    /// Linux scripts
    pub linux_scripts_subdir: &'static str,
    /// Linux policies
    pub linux_policies_subdir: &'static str,
    /// Linux reports
    pub linux_reports_subdir: &'static str,
    /// Linux software
    pub linux_software_subdir: &'static str,

    // ── Android paths ────────────────────────────────────────
    /// Android configuration profiles
    pub android_profiles_subdir: &'static str,
    /// Android managed app configurations
    pub android_managed_apps_subdir: &'static str,

    // ── Cross-platform paths ─────────────────────────────────
    /// Cross-platform policies
    pub all_policies_subdir: &'static str,
    /// Cross-platform reports
    pub all_reports_subdir: &'static str,
    /// Cross-platform icons
    pub all_icons_subdir: &'static str,
}

impl FleetLayout {
    /// Fleet v4.83+ layout — definitive structure from `fleetctl new` (April 2026+).
    ///
    /// Key changes from v4.82:
    /// - `declaration-profiles/` separated from `configuration-profiles/`
    /// - `commands/`, `enrollment-profiles/` directories for macOS
    /// - Per-platform `policies/`, `reports/`, `scripts/`, `software/`
    /// - iOS, iPadOS, Android platform directories
    /// - `paths:` glob patterns in fleet YAML (not `path:` per file)
    pub fn v4_83() -> Self {
        Self {
            version: FleetLayoutVersion::V4_83,
            platforms_dir: "platforms",
            fleets_dir: "fleets",
            labels_dir: "labels",
            unassigned_filename: "unassigned.yml",
            unassigned_name: "Unassigned",
            settings_key: "settings",
            agent_options_path: "platforms/all/agent-options.yml",

            // macOS
            macos_profiles_subdir: "platforms/macos/configuration-profiles",
            macos_declarations_subdir: "platforms/macos/declaration-profiles",
            macos_commands_subdir: "platforms/macos/commands",
            macos_enrollment_subdir: "platforms/macos/enrollment-profiles",
            macos_scripts_subdir: "platforms/macos/scripts",
            macos_policies_subdir: "platforms/macos/policies",
            macos_reports_subdir: "platforms/macos/reports",
            macos_software_subdir: "platforms/macos/software",

            // iOS
            ios_profiles_subdir: "platforms/ios/configuration-profiles",
            ios_declarations_subdir: "platforms/ios/declaration-profiles",

            // iPadOS
            ipados_profiles_subdir: "platforms/ipados/configuration-profiles",
            ipados_declarations_subdir: "platforms/ipados/declaration-profiles",

            // Windows
            windows_profiles_subdir: "platforms/windows/configuration-profiles",
            windows_scripts_subdir: "platforms/windows/scripts",
            windows_policies_subdir: "platforms/windows/policies",
            windows_reports_subdir: "platforms/windows/reports",
            windows_software_subdir: "platforms/windows/software",

            // Linux
            linux_scripts_subdir: "platforms/linux/scripts",
            linux_policies_subdir: "platforms/linux/policies",
            linux_reports_subdir: "platforms/linux/reports",
            linux_software_subdir: "platforms/linux/software",

            // Android
            android_profiles_subdir: "platforms/android/configuration-profiles",
            android_managed_apps_subdir: "platforms/android/managed-app-configurations",

            // Cross-platform
            all_policies_subdir: "platforms/all/policies",
            all_reports_subdir: "platforms/all/reports",
            all_icons_subdir: "platforms/all/icons",
        }
    }

    /// Fleet v4.82 layout.
    pub fn v4_82() -> Self {
        Self {
            version: FleetLayoutVersion::V4_82,
            platforms_dir: "platforms",
            fleets_dir: "fleets",
            labels_dir: "labels",
            unassigned_filename: "unassigned.yml",
            unassigned_name: "Unassigned",
            settings_key: "settings",
            agent_options_path: "platforms/all/agent-options.yml",

            macos_profiles_subdir: "platforms/macos/configuration-profiles",
            macos_declarations_subdir: "platforms/macos/configuration-profiles", // DDM mixed in
            macos_commands_subdir: "platforms/macos/commands",
            macos_enrollment_subdir: "platforms/macos/enrollment-profiles",
            macos_scripts_subdir: "platforms/macos/scripts",
            macos_policies_subdir: "platforms/macos/policies",
            macos_reports_subdir: "platforms/macos/reports",
            macos_software_subdir: "platforms/macos/software",

            ios_profiles_subdir: "platforms/ios/configuration-profiles",
            ios_declarations_subdir: "platforms/ios/configuration-profiles",

            ipados_profiles_subdir: "platforms/ipados/configuration-profiles",
            ipados_declarations_subdir: "platforms/ipados/configuration-profiles",

            windows_profiles_subdir: "platforms/windows/configuration-profiles",
            windows_scripts_subdir: "platforms/windows/scripts",
            windows_policies_subdir: "platforms/windows/policies",
            windows_reports_subdir: "platforms/windows/reports",
            windows_software_subdir: "platforms/windows/software",

            linux_scripts_subdir: "platforms/linux/scripts",
            linux_policies_subdir: "platforms/linux/policies",
            linux_reports_subdir: "platforms/linux/reports",
            linux_software_subdir: "platforms/linux/software",

            android_profiles_subdir: "platforms/android/configuration-profiles",
            android_managed_apps_subdir: "platforms/android/managed-app-configurations",

            all_policies_subdir: "platforms/all/policies",
            all_reports_subdir: "platforms/all/reports",
            all_icons_subdir: "platforms/all/icons",
        }
    }

    /// Legacy layout (pre-v4.82, for backwards compatibility).
    pub fn legacy() -> Self {
        Self {
            version: FleetLayoutVersion::Legacy,
            platforms_dir: "lib",
            fleets_dir: "fleets",
            labels_dir: "lib/all/labels",
            unassigned_filename: "no-team.yml",
            unassigned_name: "No team",
            settings_key: "team_settings",
            agent_options_path: "lib/agent-options.yml",

            macos_profiles_subdir: "lib/macos/configuration-profiles",
            macos_declarations_subdir: "lib/macos/configuration-profiles",
            macos_commands_subdir: "lib/macos/commands",
            macos_enrollment_subdir: "lib/macos/enrollment-profiles",
            macos_scripts_subdir: "lib/macos/scripts",
            macos_policies_subdir: "lib/macos/policies",
            macos_reports_subdir: "lib/macos/reports",
            macos_software_subdir: "lib/macos/software",

            ios_profiles_subdir: "lib/ios/configuration-profiles",
            ios_declarations_subdir: "lib/ios/configuration-profiles",

            ipados_profiles_subdir: "lib/ipados/configuration-profiles",
            ipados_declarations_subdir: "lib/ipados/configuration-profiles",

            windows_profiles_subdir: "lib/windows/configuration-profiles",
            windows_scripts_subdir: "lib/windows/scripts",
            windows_policies_subdir: "lib/windows/policies",
            windows_reports_subdir: "lib/windows/reports",
            windows_software_subdir: "lib/windows/software",

            linux_scripts_subdir: "lib/linux/scripts",
            linux_policies_subdir: "lib/linux/policies",
            linux_reports_subdir: "lib/linux/reports",
            linux_software_subdir: "lib/linux/software",

            android_profiles_subdir: "lib/android/configuration-profiles",
            android_managed_apps_subdir: "lib/android/managed-app-configurations",

            all_policies_subdir: "lib/all/policies",
            all_reports_subdir: "lib/all/reports",
            all_icons_subdir: "lib/all/icons",
        }
    }

    /// Build from a named version.
    pub fn from_version(version: FleetLayoutVersion) -> Self {
        version.layout()
    }
}

impl Default for FleetLayout {
    fn default() -> Self {
        Self::v4_83()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_v4_83_layout() {
        let layout = FleetLayout::v4_83();
        assert_eq!(layout.version, FleetLayoutVersion::V4_83);
        assert_eq!(layout.platforms_dir, "platforms");
        assert_eq!(layout.fleets_dir, "fleets");
        assert_eq!(layout.labels_dir, "labels");
        assert_eq!(layout.unassigned_filename, "unassigned.yml");
        assert_eq!(layout.settings_key, "settings");
        // v4.83: declarations separated from configuration profiles
        assert_ne!(
            layout.macos_profiles_subdir,
            layout.macos_declarations_subdir
        );
        assert_eq!(
            layout.macos_declarations_subdir,
            "platforms/macos/declaration-profiles"
        );
        assert_eq!(layout.macos_commands_subdir, "platforms/macos/commands");
        assert_eq!(
            layout.macos_enrollment_subdir,
            "platforms/macos/enrollment-profiles"
        );
    }

    #[test]
    fn test_v4_82_declarations_mixed() {
        let layout = FleetLayout::v4_82();
        // v4.82: declarations were in the same dir as configuration profiles
        assert_eq!(
            layout.macos_profiles_subdir,
            layout.macos_declarations_subdir
        );
    }

    #[test]
    fn test_legacy_layout() {
        let layout = FleetLayout::legacy();
        assert_eq!(layout.version, FleetLayoutVersion::Legacy);
        assert_eq!(layout.platforms_dir, "lib");
        assert_eq!(layout.labels_dir, "lib/all/labels");
        assert_eq!(layout.unassigned_filename, "no-team.yml");
        assert_eq!(layout.settings_key, "team_settings");
    }

    #[test]
    fn test_default_is_v4_83() {
        let default = FleetLayout::default();
        assert_eq!(default.version, FleetLayoutVersion::V4_83);
        assert_eq!(default.platforms_dir, "platforms");
        assert_eq!(
            default.macos_declarations_subdir,
            "platforms/macos/declaration-profiles"
        );
    }

    #[test]
    fn test_from_version() {
        let layout = FleetLayout::from_version(FleetLayoutVersion::Legacy);
        assert_eq!(layout.platforms_dir, "lib");
    }

    #[test]
    fn test_version_from_name() {
        assert_eq!(
            FleetLayoutVersion::from_name("v4.83"),
            Some(FleetLayoutVersion::V4_83)
        );
        assert_eq!(
            FleetLayoutVersion::from_name("current"),
            Some(FleetLayoutVersion::V4_83)
        );
        assert_eq!(
            FleetLayoutVersion::from_name("latest"),
            Some(FleetLayoutVersion::V4_83)
        );
        assert_eq!(
            FleetLayoutVersion::from_name("v4.82"),
            Some(FleetLayoutVersion::V4_82)
        );
        assert_eq!(
            FleetLayoutVersion::from_name("legacy"),
            Some(FleetLayoutVersion::Legacy)
        );
        assert_eq!(FleetLayoutVersion::from_name("unknown"), None);
    }

    #[test]
    fn test_version_all_covers_all_variants() {
        let all = FleetLayoutVersion::all();
        assert!(all.contains(&FleetLayoutVersion::V4_83));
        assert!(all.contains(&FleetLayoutVersion::V4_82));
        assert!(all.contains(&FleetLayoutVersion::Legacy));
    }

    #[test]
    fn test_all_platforms_present() {
        let layout = FleetLayout::v4_83();
        assert!(layout.ios_profiles_subdir.contains("ios"));
        assert!(layout.ipados_profiles_subdir.contains("ipados"));
        assert!(layout.android_profiles_subdir.contains("android"));
        assert!(layout.windows_profiles_subdir.contains("windows"));
        assert!(layout.linux_scripts_subdir.contains("linux"));
    }
}
