//! Fleet `GitOps` structure generator
//!
//! Generates a complete Fleet `GitOps` directory structure matching the official
//! fleet-gitops reference: <https://github.com/fleetdm/fleet-gitops>
//!
//! Uses `FleetLayout` for all path conventions (Fleet v4.82+).

use crate::config::GlobSection;
use crate::models::{
    Controls, CustomSetting, EnrollSecret, Features, FleetConfig, FleetGlobalConfig, FleetSettings,
    OrgInfo, OrgSettings, PlatformSettings, Script, ServerSettings, Software,
};
use anyhow::Result;
use contour_core::fleet_layout::FleetLayout;
use std::path::{Path, PathBuf};

/// Per-fleet glob decisions threaded from `mscp.toml` into fleet YAML emission.
///
/// `None` for a section means "no glob — emit one literal `path:` per item,
/// same as before the feature existed". `Some` means "emit a single `paths:`
/// entry plus one literal `path:` per exception".
#[derive(Debug, Clone, Default)]
pub struct GlobPlan<'a> {
    pub profiles: Option<&'a GlobSection>,
    pub scripts: Option<&'a GlobSection>,
}

/// Generator for complete Fleet `GitOps` directory structure
#[derive(Debug)]
pub struct FleetGitOpsGenerator {
    output_base: PathBuf,
    layout: FleetLayout,
}

impl FleetGitOpsGenerator {
    /// Create a new generator with the given output base and layout.
    pub fn new<P: AsRef<Path>>(output_base: P, layout: FleetLayout) -> Self {
        Self {
            output_base: output_base.as_ref().to_path_buf(),
            layout,
        }
    }

    /// Create a new generator with the default Fleet v4.82+ layout.
    pub fn new_default<P: AsRef<Path>>(output_base: P) -> Self {
        Self::new(output_base, FleetLayout::default())
    }

    /// Generate the complete Fleet `GitOps` structure
    pub fn generate_structure(&self) -> Result<()> {
        // Create required directories
        std::fs::create_dir_all(self.output_base.join(self.layout.platforms_dir))?;
        std::fs::create_dir_all(self.output_base.join(self.layout.fleets_dir))?;

        // Generate global files. Agent options are intentionally NOT emitted —
        // the canonical `fleetctl new` scaffold ships no agent-options.yml (agent
        // config is left to Fleet defaults / the target repo). `generate_agent_options`
        // remains available as opt-in API for callers that want it.
        self.generate_default_yml()?;
        self.generate_unassigned_yml()?;

        Ok(())
    }

    /// Generate default.yml with `org_settings` and global configuration
    pub fn generate_default_yml(&self) -> Result<PathBuf> {
        let config = FleetGlobalConfig {
            policies: Some(Vec::new()),
            reports: Some(Vec::new()),
            // No agent_options reference — matches `fleetctl new` (northstar).
            agent_options: None,
            controls: Some(Controls {
                macos_settings: None,
                ios_settings: None,
                scripts: None,
            }),
            org_settings: Some(OrgSettings {
                server_settings: Some(ServerSettings {
                    server_url: "$FLEET_URL".to_string(),
                }),
                org_info: Some(OrgInfo {
                    org_name: "Fleet".to_string(),
                }),
                secrets: Some(vec![EnrollSecret {
                    secret: "$FLEET_GLOBAL_ENROLL_SECRET".to_string(),
                }]),
                features: Some(Features {
                    enable_host_users: Some(true),
                    enable_software_inventory: Some(true),
                }),
            }),
            labels: None, // Labels are added per-baseline via add_label_to_default_yml
        };

        let file_path = self.output_base.join("default.yml");

        let header = format!(
            r#"# Fleet GitOps - Global Configuration (Fleet v4.82+)
#
# For Fleet Free:
# - This file updates policies, reports, and controls for all hosts.
#
# For Fleet Premium:
# - This file updates policies and reports that run on all hosts ("All teams").
# - Remove "controls" and add this to your YAML files in {fleets_dir}/ instead.
#
# Generated by contour mscp - https://github.com/macadmins/contour

"#,
            fleets_dir = self.layout.fleets_dir,
        );

        let yaml_content = yaml_serde::to_string(&config)?;
        std::fs::write(&file_path, format!("{header}{yaml_content}"))?;

        tracing::info!("Generated default.yml: {}", file_path.display());
        Ok(file_path)
    }

    /// Generate the unassigned hosts YAML file (Fleet v4.82+: unassigned.yml)
    pub fn generate_unassigned_yml(&self) -> Result<PathBuf> {
        let fleets_dir = self.output_base.join(self.layout.fleets_dir);
        std::fs::create_dir_all(&fleets_dir)?;

        let file_path = fleets_dir.join(self.layout.unassigned_filename);

        let content = format!(
            r#"# Fleet GitOps - {unassigned_name} Configuration (Fleet v4.82+)
#
# This file updates policies, controls, and software for hosts assigned to "{unassigned_name}."
# To update reports and agent options for these hosts, use default.yml.
#
# Generated by contour mscp - https://github.com/macadmins/contour

name: {unassigned_name}
policies:
controls:
software:
"#,
            unassigned_name = self.layout.unassigned_name,
        );

        std::fs::write(&file_path, content)?;

        tracing::info!(
            "Generated {}: {}",
            self.layout.unassigned_filename,
            file_path.display()
        );
        Ok(file_path)
    }

    /// Deprecated: use `generate_unassigned_yml` instead.
    #[deprecated(note = "renamed to generate_unassigned_yml for Fleet v4.82+")]
    #[allow(dead_code, reason = "reserved for future use")]
    pub fn generate_no_fleet_yml(&self) -> Result<PathBuf> {
        self.generate_unassigned_yml()
    }

    /// Generate a fleet YAML file for a specific baseline
    ///
    /// # Arguments
    /// * `baseline_name` - Name of the baseline (e.g., `cis_lvl1`)
    /// * `profile_paths` - Paths to mobileconfig files
    /// * `script_paths` - Paths to script files (audit, remediate)
    pub fn generate_fleet_yml(
        &self,
        baseline_name: &str,
        profile_paths: &[PathBuf],
        script_paths: &[(PathBuf, Option<PathBuf>)], // (audit, remediate)
    ) -> Result<PathBuf> {
        self.generate_fleet_yml_with_policies(baseline_name, profile_paths, script_paths, None)
    }

    /// Generate a fleet YAML file for a specific baseline, optionally including
    /// a policies path reference.
    pub fn generate_fleet_yml_with_policies(
        &self,
        baseline_name: &str,
        profile_paths: &[PathBuf],
        script_paths: &[(PathBuf, Option<PathBuf>)],
        policy_path: Option<&Path>,
    ) -> Result<PathBuf> {
        self.generate_fleet_yml_with_glob_plan(
            baseline_name,
            profile_paths,
            script_paths,
            policy_path,
            &GlobPlan::default(),
        )
    }

    /// Glob-aware variant: collapses items into a single `paths:` glob where
    /// the plan enables it, and emits literal `path:` entries for exceptions.
    ///
    /// When no plan is provided (`GlobPlan::default()`), behaviour is identical
    /// to the legacy per-item emission.
    pub fn generate_fleet_yml_with_glob_plan(
        &self,
        baseline_name: &str,
        profile_paths: &[PathBuf],
        script_paths: &[(PathBuf, Option<PathBuf>)],
        policy_path: Option<&Path>,
        glob_plan: &GlobPlan<'_>,
    ) -> Result<PathBuf> {
        let fleets_dir = self.output_base.join(self.layout.fleets_dir);
        std::fs::create_dir_all(&fleets_dir)?;

        let fleet_name = baseline_name.replace('_', "-");
        let label_name = format!("mscp-{baseline_name}");
        let secret_var = format!(
            "FLEET_{}_ENROLL_SECRET",
            baseline_name.to_uppercase().replace('-', "_")
        );

        let custom_settings = self.emit_profiles_section(
            baseline_name,
            &label_name,
            profile_paths,
            glob_plan.profiles,
        )?;
        let scripts = self.emit_scripts_section(baseline_name, script_paths, glob_plan.scripts)?;

        // Build fleet settings as yaml_serde::Value
        let fleet_settings = FleetSettings {
            secrets: Some(vec![EnrollSecret {
                secret: format!("${secret_var}"),
            }]),
            features: Some(Features {
                enable_host_users: Some(true),
                enable_software_inventory: Some(true),
            }),
        };

        // Build policies -- either a path reference to generated policy file, or empty
        let policies_value: Vec<yaml_serde::Value> = if let Some(p) = policy_path {
            let policy_filename = p.file_name().and_then(|s| s.to_str()).unwrap_or_default();
            // Fleet v4.83+: policies live at platforms/macos/policies/{baseline}/.
            let relative_policy_path = format!(
                "../{}/{baseline_name}/{policy_filename}",
                self.layout.macos_policies_subdir
            );

            let mut map = yaml_serde::Mapping::new();
            map.insert(
                yaml_serde::Value::String("path".to_string()),
                yaml_serde::Value::String(relative_policy_path),
            );
            vec![yaml_serde::Value::Mapping(map)]
        } else {
            Vec::new()
        };

        let config = FleetConfig {
            name: Some(fleet_name.clone()),
            policies: Some(policies_value),
            reports: Some(Vec::new()),
            // No agent_options — matches `fleetctl new` (northstar).
            agent_options: None,
            controls: Some(Controls {
                macos_settings: if custom_settings.is_empty() {
                    None
                } else {
                    Some(PlatformSettings {
                        custom_settings: Some(custom_settings),
                    })
                },
                ios_settings: None,
                scripts: if scripts.is_empty() {
                    None
                } else {
                    Some(scripts)
                },
            }),
            settings: Some(yaml_serde::to_value(&fleet_settings)?),
            software: Some(Software::default()),
        };

        let file_path = fleets_dir.join(format!("{baseline_name}.yml"));

        let header = format!(
            r"# Fleet GitOps - Fleet Configuration: {fleet_name} (Fleet v4.82+)
#
# mSCP Baseline: {baseline_name}
# Profiles: {profiles_dir}/{baseline_name}/
# Scripts:  {scripts_dir}/{baseline_name}/
#
# Required environment variables:
#   - ${secret_var}
#
# Generated by contour mscp - https://github.com/macadmins/contour

",
            profiles_dir = self.layout.macos_profiles_subdir,
            scripts_dir = self.layout.macos_scripts_subdir,
        );

        let yaml_content = yaml_serde::to_string(&config)?;
        std::fs::write(&file_path, format!("{header}{yaml_content}"))?;

        tracing::info!("Generated fleet YAML: {}", file_path.display());
        Ok(file_path)
    }

    /// Emit the `configuration_profiles` entries for a fleet YAML.
    ///
    /// - If `section` is `None` or `section.enabled == false`, emits one literal
    ///   `path:` entry per profile with the baseline label (legacy behaviour).
    /// - If `section.enabled == true`, emits one `paths:` glob (no labels —
    ///   Fleet forbids labels on glob entries, which is why the interactive
    ///   flow requires `drop_labels = true` to reach this state) plus one
    ///   literal `path:` entry per exception. Exceptions carry the exception's
    ///   own subfolder + labels.
    ///
    /// Invariant: every returned `CustomSetting` has exactly one of
    /// `path`/`paths` set and labels only on `path:` entries.
    fn emit_profiles_section(
        &self,
        baseline_name: &str,
        label_name: &str,
        profile_paths: &[PathBuf],
        section: Option<&GlobSection>,
    ) -> Result<Vec<CustomSetting>> {
        // Fleet v4.83+: profiles live at platforms/macos/configuration-profiles/{baseline}/.
        let base_dir = format!("../{}/{baseline_name}", self.layout.macos_profiles_subdir);

        let Some(section) = section.filter(|s| s.enabled) else {
            // Legacy path: one literal per profile, all sharing the baseline label.
            return profile_paths
                .iter()
                .map(|p| {
                    let filename = p.file_name().and_then(|s| s.to_str()).unwrap_or_default();
                    let cs = CustomSetting {
                        path: Some(format!("{base_dir}/{filename}")),
                        paths: None,
                        labels_include_all: Some(vec![label_name.to_string()]),
                        labels_include_any: None,
                        labels_exclude_any: None,
                    };
                    cs.validate()?;
                    Ok(cs)
                })
                .collect();
        };

        if !section.drop_labels {
            anyhow::bail!(
                "configuration_profiles glob enabled for baseline '{baseline_name}' without \
                 drop_labels=true — Fleet does not allow labels on `paths:` entries. \
                 Re-run with --interactive to accept the label-drop, or disable the glob."
            );
        }

        let mut out = Vec::with_capacity(section.exceptions.len() + 1);

        // One `paths:` entry for the flat directory.
        let glob_entry = CustomSetting {
            path: None,
            paths: Some(format!("{base_dir}/*.mobileconfig")),
            labels_include_all: None,
            labels_include_any: None,
            labels_exclude_any: None,
        };
        glob_entry.validate()?;
        out.push(glob_entry);

        // One literal `path:` entry per exception.
        for exc in &section.exceptions {
            let subfolder = exc
                .subfolder
                .as_deref()
                .map(|s| format!("/{s}"))
                .unwrap_or_default();
            let entry = CustomSetting {
                path: Some(format!("{base_dir}{subfolder}/{}", exc.filename)),
                paths: None,
                labels_include_all: non_empty_vec(&exc.labels_include_all),
                labels_include_any: non_empty_vec(&exc.labels_include_any),
                labels_exclude_any: non_empty_vec(&exc.labels_exclude_any),
            };
            entry.validate()?;
            out.push(entry);
        }

        Ok(out)
    }

    /// Emit the `controls.scripts` entries for a fleet YAML.
    ///
    /// Scripts have no labels in Fleet, so globbing is unconditionally safe —
    /// no `drop_labels` check required.
    fn emit_scripts_section(
        &self,
        baseline_name: &str,
        script_paths: &[(PathBuf, Option<PathBuf>)],
        section: Option<&GlobSection>,
    ) -> Result<Vec<Script>> {
        // Fleet v4.83+: scripts live at platforms/macos/scripts/{baseline}/.
        let base_dir = format!("../{}/{baseline_name}", self.layout.macos_scripts_subdir);

        let flatten = |pairs: &[(PathBuf, Option<PathBuf>)]| -> Vec<String> {
            let mut names = Vec::with_capacity(pairs.len() * 2);
            for (audit, remediate) in pairs {
                if let Some(n) = audit.file_name().and_then(|s| s.to_str()) {
                    names.push(n.to_string());
                }
                if let Some(r) = remediate.as_ref()
                    && let Some(n) = r.file_name().and_then(|s| s.to_str())
                {
                    names.push(n.to_string());
                }
            }
            names
        };

        let Some(section) = section.filter(|s| s.enabled) else {
            return flatten(script_paths)
                .into_iter()
                .map(|n| {
                    let s = Script {
                        path: Some(format!("{base_dir}/{n}")),
                        paths: None,
                    };
                    s.validate()?;
                    Ok(s)
                })
                .collect();
        };

        let mut out = Vec::with_capacity(section.exceptions.len() + 1);

        let glob_entry = Script {
            path: None,
            paths: Some(format!("{base_dir}/*.sh")),
        };
        glob_entry.validate()?;
        out.push(glob_entry);

        for exc in &section.exceptions {
            let subfolder = exc
                .subfolder
                .as_deref()
                .map(|s| format!("/{s}"))
                .unwrap_or_default();
            let entry = Script {
                path: Some(format!("{base_dir}{subfolder}/{}", exc.filename)),
                paths: None,
            };
            entry.validate()?;
            out.push(entry);
        }

        Ok(out)
    }

    /// Add a label path reference to default.yml using line-based insertion.
    ///
    /// This preserves comments and formatting by inserting directly into the YAML text
    /// rather than round-tripping through serde.
    pub fn add_label_to_default_yml(&self, label_path: &str) -> Result<()> {
        let file_path = self.output_base.join("default.yml");

        if !file_path.exists() {
            anyhow::bail!("default.yml does not exist. Run generate_structure() first.");
        }

        // Read existing content
        let content = std::fs::read_to_string(&file_path)?;

        // Check if already present
        if content.contains(label_path) {
            tracing::info!("Label reference already present in default.yml: {label_path}");
            return Ok(());
        }

        let entry_line = format!("- path: {label_path}");

        // Try line-based insertion
        let new_content = if let Some(result) = insert_label_entry(&content, &entry_line) {
            result
        } else {
            // Fallback: append labels section at end
            let mut result = content.clone();
            if !result.ends_with('\n') {
                result.push('\n');
            }
            result.push_str(&format!("labels:\n  {entry_line}\n"));
            result
        };

        std::fs::write(&file_path, new_content)?;

        tracing::info!("Added label reference to default.yml: {label_path}");
        Ok(())
    }

    /// Generate a fragment-style default.yml containing only labels section.
    ///
    /// This is used in fragment mode where org_settings, agent_options, and controls
    /// are not included (they come from the target repo).
    pub fn generate_fragment_default_yml(&self, label_paths: &[String]) -> Result<PathBuf> {
        let file_path = self.output_base.join("default.yml");

        let mut content = String::from(
            "# Fleet GitOps - Fragment Configuration (labels only)\n\
             #\n\
             # This fragment provides label definitions to be merged into a target repo.\n\
             #\n\
             # Generated by contour mscp - https://github.com/macadmins/contour\n\
             \n",
        );

        if label_paths.is_empty() {
            content.push_str("labels:\n");
        } else {
            content.push_str("labels:\n");
            for lp in label_paths {
                content.push_str(&format!("  - path: {lp}\n"));
            }
        }

        content.push_str("\nreports:\n\npolicies:\n");

        std::fs::write(&file_path, &content)?;
        tracing::info!("Generated fragment default.yml: {}", file_path.display());
        Ok(file_path)
    }

    /// Generate a `fragment.toml` manifest at the output root.
    pub fn generate_fragment_toml(
        &self,
        name: &str,
        label_paths: &[String],
        profile_entries: &[contour_core::fragment::ProfileEntry],
        policy_entries: &[contour_core::fragment::SimpleEntry],
        lib_files: &[String],
    ) -> Result<PathBuf> {
        let manifest = contour_core::fragment::FragmentManifest {
            fragment: contour_core::fragment::FragmentMeta {
                name: name.to_string(),
                version: "1.0.0".to_string(),
                description: format!("mSCP baseline: {name}"),
                generator: "contour-mscp".to_string(),
            },
            default_yml: contour_core::fragment::DefaultYmlEntries {
                label_paths: label_paths.to_vec(),
                report_paths: Vec::new(),
                // `default.yml` sits at the repo root, so its policy paths
                // need one fewer `../` than the fleets/-relative form reused
                // below for `fleet_entries.policies`.
                policy_paths: policy_entries
                    .iter()
                    .map(|e| Self::fleets_path_to_root_path(&e.path))
                    .collect(),
            },
            fleet_entries: contour_core::fragment::FleetEntries {
                profiles: profile_entries.to_vec(),
                reports: Vec::new(),
                policies: policy_entries.to_vec(),
                software: Vec::new(),
            },
            lib_files: contour_core::fragment::LibFiles {
                copy: lib_files.to_vec(),
            },
            scripts: contour_core::fragment::ScriptEntries::default(),
        };

        let file_path = self.output_base.join("fragment.toml");
        manifest.save(&file_path)?;
        tracing::info!("Generated fragment.toml: {}", file_path.display());
        Ok(file_path)
    }

    /// Convert a fleets/-relative path (`../platforms/…`) to a repo-root-
    /// relative path (`./platforms/…`).
    ///
    /// Fleet files live in `fleets/`, one level below the repo root, so they
    /// reference shared artifacts with a leading `../`. `default.yml` lives
    /// at the root, so paths referenced from it carry one fewer `../`.
    fn fleets_path_to_root_path(path: &str) -> String {
        match path.strip_prefix("../") {
            Some(rest) => format!("./{rest}"),
            None => path.to_string(),
        }
    }

    /// Check if default.yml already exists
    pub fn default_yml_exists(&self) -> bool {
        self.output_base.join("default.yml").exists()
    }

    /// Check if unassigned hosts YAML already exists
    #[allow(dead_code, reason = "reserved for future use")]
    pub fn unassigned_yml_exists(&self) -> bool {
        self.output_base
            .join(self.layout.fleets_dir)
            .join(self.layout.unassigned_filename)
            .exists()
    }
}

/// Wrap a `Vec<String>` in `Some` only if it has elements, so empty label
/// lists serialize as "field absent" instead of as an empty YAML sequence.
fn non_empty_vec(v: &[String]) -> Option<Vec<String>> {
    if v.is_empty() { None } else { Some(v.to_vec()) }
}

/// Insert a label entry line into existing YAML content.
///
/// Finds the `labels:` section and inserts the entry after the last existing
/// `- path:` entry (or right after `labels:` if none exist). Preserves comments
/// and formatting.
fn insert_label_entry(content: &str, entry_line: &str) -> Option<String> {
    let lines: Vec<&str> = content.lines().collect();

    // Find the `labels:` line (top-level, no indentation)
    let labels_idx = lines.iter().position(|l| {
        let trimmed = l.trim();
        trimmed == "labels:" || trimmed.starts_with("labels:")
    })?;

    // Find the indentation to use (look at existing entries under labels:)
    let indent = "  ";

    // Find insertion point: after last `- path:` entry under labels, or right after `labels:`
    let mut insert_idx = labels_idx + 1;
    let mut i = labels_idx + 1;
    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim();

        // Stop if we hit another top-level key
        if !trimmed.is_empty() && !trimmed.starts_with('#') && !line.starts_with(' ') {
            break;
        }

        // Track last label entry position
        if trimmed.starts_with("- path:") {
            insert_idx = i + 1;
        }

        i += 1;
    }

    let mut result = Vec::with_capacity(lines.len() + 1);
    for (idx, line) in lines.iter().enumerate() {
        result.push(line.to_string());
        if idx == insert_idx - 1 {
            result.push(format!("{indent}{entry_line}"));
        }
    }

    // If insert_idx is past the end, append
    if insert_idx >= lines.len() {
        result.push(format!("{indent}{entry_line}"));
    }

    Some(result.join("\n") + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_fleets_path_to_root_path() {
        // A fleets/-relative path drops one `../` for the repo-root form.
        assert_eq!(
            FleetGitOpsGenerator::fleets_path_to_root_path(
                "../platforms/macos/policies/800-53r5_high/p.yml"
            ),
            "./platforms/macos/policies/800-53r5_high/p.yml"
        );
        // An already-root-relative path is left unchanged.
        assert_eq!(
            FleetGitOpsGenerator::fleets_path_to_root_path("./labels/mscp.labels.yml"),
            "./labels/mscp.labels.yml"
        );
    }

    #[test]
    fn test_generate_default_yml() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());

        let path = generator.generate_default_yml().unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("$FLEET_URL"));
        assert!(content.contains("$FLEET_GLOBAL_ENROLL_SECRET"));
        // No agent_options reference — matches `fleetctl new` (northstar).
        assert!(!content.contains("agent_options"));
    }

    #[test]
    fn test_generate_unassigned_yml() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());

        let path = generator.generate_unassigned_yml().unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        let layout = FleetLayout::default();
        assert!(content.contains(&format!("name: {}", layout.unassigned_name)));
    }

    #[test]
    fn test_generate_fleet_yml() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let layout = FleetLayout::default();

        let profiles = vec![PathBuf::from("profiles/com.apple.test.mobileconfig")];
        let scripts = vec![(
            PathBuf::from("scripts/test_audit.sh"),
            Some(PathBuf::from("scripts/test_remediate.sh")),
        )];

        let path = generator
            .generate_fleet_yml("cis_lvl1", &profiles, &scripts)
            .unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("name: cis-lvl1"));
        // Fleet v4.83+: profiles/scripts under platforms/macos/{kind}/{baseline}/.
        assert!(content.contains(&format!("../{}/cis_lvl1/", layout.macos_profiles_subdir)));
        assert!(content.contains(&format!("../{}/cis_lvl1/", layout.macos_scripts_subdir)));
        assert!(content.contains("$FLEET_CIS_LVL1_ENROLL_SECRET"));
    }

    #[test]
    fn test_generate_structure() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let layout = FleetLayout::default();

        generator.generate_structure().unwrap();

        assert!(temp_dir.path().join("default.yml").exists());
        // agent-options.yml is intentionally not generated (northstar parity).
        assert!(!temp_dir.path().join(layout.agent_options_path).exists());
        assert!(
            temp_dir
                .path()
                .join(layout.fleets_dir)
                .join(layout.unassigned_filename)
                .exists()
        );
    }

    #[test]
    fn emit_profiles_section_glob_off_matches_legacy() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let profiles = vec![
            PathBuf::from("a.mobileconfig"),
            PathBuf::from("b.mobileconfig"),
        ];

        let out = generator
            .emit_profiles_section("cis_lvl1", "mscp-cis_lvl1", &profiles, None)
            .unwrap();
        assert_eq!(out.len(), 2);
        for cs in &out {
            assert!(cs.path.is_some());
            assert!(cs.paths.is_none());
            assert_eq!(
                cs.labels_include_all.as_deref(),
                Some(&["mscp-cis_lvl1".to_string()][..])
            );
        }
    }

    #[test]
    fn emit_profiles_section_glob_on_emits_single_paths_plus_exceptions() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let profiles = vec![
            PathBuf::from("com.apple.finder.mobileconfig"),
            PathBuf::from("com.apple.screensaver.mobileconfig"),
        ];
        let section = GlobSection {
            enabled: true,
            drop_labels: true,
            exceptions: vec![crate::config::GlobException {
                filename: "com.apple.screensaver.mobileconfig".to_string(),
                subfolder: Some("screensaver".to_string()),
                labels_include_all: vec!["custom-screensaver".to_string()],
                labels_include_any: vec![],
                labels_exclude_any: vec![],
            }],
        };

        let out = generator
            .emit_profiles_section("cis_lvl1", "mscp-cis_lvl1", &profiles, Some(&section))
            .unwrap();
        assert_eq!(out.len(), 2);

        // First entry: glob with no labels (Fleet v4.83+: under platforms/macos/configuration-profiles/).
        assert!(out[0].path.is_none());
        assert_eq!(
            out[0].paths.as_deref(),
            Some(
                format!(
                    "../{}/cis_lvl1/*.mobileconfig",
                    FleetLayout::default().macos_profiles_subdir
                )
                .as_str()
            )
        );
        assert!(out[0].labels_include_all.is_none());

        // Second entry: literal path in subfolder, carries the custom label.
        assert!(out[1].paths.is_none());
        assert_eq!(
            out[1].path.as_deref(),
            Some(
                format!(
                    "../{}/cis_lvl1/screensaver/com.apple.screensaver.mobileconfig",
                    FleetLayout::default().macos_profiles_subdir
                )
                .as_str()
            )
        );
        assert_eq!(
            out[1].labels_include_all.as_deref(),
            Some(&["custom-screensaver".to_string()][..])
        );
    }

    #[test]
    fn emit_profiles_section_refuses_glob_without_drop_labels() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let profiles = vec![
            PathBuf::from("a.mobileconfig"),
            PathBuf::from("b.mobileconfig"),
        ];
        let section = GlobSection {
            enabled: true,
            drop_labels: false,
            exceptions: vec![],
        };

        let err = generator
            .emit_profiles_section("cis_lvl1", "mscp-cis_lvl1", &profiles, Some(&section))
            .unwrap_err();
        assert!(err.to_string().contains("drop_labels"));
    }

    #[test]
    fn emit_scripts_section_glob_on_emits_single_paths_plus_exceptions() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let scripts = vec![
            (
                PathBuf::from("audit.sh"),
                Some(PathBuf::from("remediate.sh")),
            ),
            (PathBuf::from("special_audit.sh"), None),
        ];
        let section = GlobSection {
            enabled: true,
            drop_labels: false,
            exceptions: vec![crate::config::GlobException {
                filename: "special_audit.sh".to_string(),
                subfolder: Some("special".to_string()),
                labels_include_all: vec![],
                labels_include_any: vec![],
                labels_exclude_any: vec![],
            }],
        };

        let out = generator
            .emit_scripts_section("cis_lvl1", &scripts, Some(&section))
            .unwrap();
        assert_eq!(out.len(), 2);
        assert!(out[0].paths.is_some());
        assert!(out[0].path.is_none());
        assert_eq!(
            out[1].path.as_deref(),
            Some(
                format!(
                    "../{}/cis_lvl1/special/special_audit.sh",
                    FleetLayout::default().macos_scripts_subdir
                )
                .as_str()
            )
        );
    }

    #[test]
    fn test_legacy_layout_paths() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new(temp_dir.path(), FleetLayout::legacy());

        generator.generate_structure().unwrap();

        assert!(temp_dir.path().join("default.yml").exists());
        assert!(!temp_dir.path().join("lib/agent-options.yml").exists());
        assert!(temp_dir.path().join("fleets/no-team.yml").exists());

        let content = std::fs::read_to_string(temp_dir.path().join("fleets/no-team.yml")).unwrap();
        assert!(content.contains("name: No team"));
    }
}
