//! Fleet `GitOps` structure generator
//!
//! Generates a complete Fleet `GitOps` directory structure matching the official
//! fleet-gitops reference: <https://github.com/fleetdm/fleet-gitops>
//!
//! Uses `FleetLayout` for all path conventions (Fleet v4.82+).

use crate::models::{
    AgentConfig, AgentConfigOptions, AgentOptions, AgentOptionsRef, Controls, CustomSetting,
    Decorators, EnrollSecret, Features, FleetGlobalConfig, FleetTeamConfig, OrgInfo, OrgSettings,
    PlatformSettings, Script, ServerSettings, Software, TeamSettings,
};
use anyhow::Result;
use contour_core::fleet_layout::FleetLayout;
use std::path::{Path, PathBuf};

/// Generator for complete Fleet `GitOps` directory structure
#[derive(Debug)]
pub struct FleetGitOpsGenerator {
    output_base: PathBuf,
    layout: FleetLayout,
}

impl FleetGitOpsGenerator {
    /// Create a new generator with the given output base and layout.
    pub fn new<P: AsRef<Path>>(output_base: P, layout: FleetLayout) -> Self {
        Self {
            output_base: output_base.as_ref().to_path_buf(),
            layout,
        }
    }

    /// Create a new generator with the default Fleet v4.82+ layout.
    pub fn new_default<P: AsRef<Path>>(output_base: P) -> Self {
        Self::new(output_base, FleetLayout::default())
    }

    /// Generate the complete Fleet `GitOps` structure
    pub fn generate_structure(&self) -> Result<()> {
        // Create required directories
        std::fs::create_dir_all(self.output_base.join(self.layout.platforms_dir))?;
        std::fs::create_dir_all(self.output_base.join(self.layout.fleets_dir))?;

        // Generate global files
        self.generate_default_yml()?;
        self.generate_agent_options()?;
        self.generate_unassigned_yml()?;

        Ok(())
    }

    /// Generate default.yml with `org_settings` and global configuration
    pub fn generate_default_yml(&self) -> Result<PathBuf> {
        let config = FleetGlobalConfig {
            policies: Some(Vec::new()),
            reports: Some(Vec::new()),
            agent_options: Some(AgentOptionsRef {
                path: format!("./{}", self.layout.agent_options_path),
            }),
            controls: Some(Controls {
                macos_settings: None,
                ios_settings: None,
                scripts: None,
            }),
            org_settings: Some(OrgSettings {
                server_settings: Some(ServerSettings {
                    server_url: "$FLEET_URL".to_string(),
                }),
                org_info: Some(OrgInfo {
                    org_name: "Fleet".to_string(),
                }),
                secrets: Some(vec![EnrollSecret {
                    secret: "$FLEET_GLOBAL_ENROLL_SECRET".to_string(),
                }]),
                features: Some(Features {
                    enable_host_users: Some(true),
                    enable_software_inventory: Some(true),
                }),
            }),
            labels: None, // Labels are added per-baseline via add_label_to_default_yml
        };

        let file_path = self.output_base.join("default.yml");

        let header = format!(
            r#"# Fleet GitOps - Global Configuration (Fleet v4.82+)
#
# For Fleet Free:
# - This file updates policies, reports, agent_options, and controls for all hosts.
#
# For Fleet Premium:
# - This file updates policies and reports that run on all hosts ("All teams").
# - Remove "controls" and add this to your YAML files in {fleets_dir}/ instead.
#
# Generated by contour mscp - https://github.com/headmin/contour

"#,
            fleets_dir = self.layout.fleets_dir,
        );

        let yaml_content = yaml_serde::to_string(&config)?;
        std::fs::write(&file_path, format!("{header}{yaml_content}"))?;

        tracing::info!("Generated default.yml: {}", file_path.display());
        Ok(file_path)
    }

    /// Generate agent-options.yml with standard osquery configuration
    pub fn generate_agent_options(&self) -> Result<PathBuf> {
        let options = AgentOptions {
            command_line_flags: None,
            config: Some(AgentConfig {
                decorators: Some(Decorators {
                    load: Some(vec![
                        "SELECT uuid AS host_uuid FROM system_info;".to_string(),
                        "SELECT hostname AS hostname FROM system_info;".to_string(),
                    ]),
                }),
                options: Some(AgentConfigOptions {
                    disable_distributed: Some(false),
                    distributed_interval: Some(10),
                    distributed_plugin: Some("tls".to_string()),
                    distributed_tls_max_attempts: Some(3),
                    logger_tls_endpoint: Some("/api/v1/osquery/log".to_string()),
                    pack_delimiter: Some("/".to_string()),
                }),
            }),
        };

        // Build the agent options path from the layout
        let file_path = self.output_base.join(self.layout.agent_options_path);
        if let Some(parent) = file_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let header = r"# Fleet GitOps - Agent Options
#
# Shared osquery agent configuration referenced by fleet files.
# See: https://fleetdm.com/docs/configuration/agent-configuration
#
# Generated by contour mscp - https://github.com/headmin/contour

";

        let yaml_content = yaml_serde::to_string(&options)?;
        std::fs::write(&file_path, format!("{header}{yaml_content}"))?;

        tracing::info!("Generated agent-options.yml: {}", file_path.display());
        Ok(file_path)
    }

    /// Generate the unassigned hosts YAML file (Fleet v4.82+: unassigned.yml)
    pub fn generate_unassigned_yml(&self) -> Result<PathBuf> {
        let fleets_dir = self.output_base.join(self.layout.fleets_dir);
        std::fs::create_dir_all(&fleets_dir)?;

        let file_path = fleets_dir.join(self.layout.unassigned_filename);

        let content = format!(
            r#"# Fleet GitOps - {unassigned_name} Configuration (Fleet v4.82+)
#
# This file updates policies, controls, and software for hosts assigned to "{unassigned_name}."
# To update reports and agent options for these hosts, use default.yml.
#
# Generated by contour mscp - https://github.com/headmin/contour

name: {unassigned_name}
policies:
controls:
software:
"#,
            unassigned_name = self.layout.unassigned_name,
        );

        std::fs::write(&file_path, content)?;

        tracing::info!(
            "Generated {}: {}",
            self.layout.unassigned_filename,
            file_path.display()
        );
        Ok(file_path)
    }

    /// Deprecated: use `generate_unassigned_yml` instead.
    #[deprecated(note = "renamed to generate_unassigned_yml for Fleet v4.82+")]
    #[allow(
        dead_code,
        reason = "kept as deprecated alias for backwards compatibility"
    )]
    pub fn generate_no_team_yml(&self) -> Result<PathBuf> {
        self.generate_unassigned_yml()
    }

    /// Generate a fleet YAML file for a specific baseline
    ///
    /// # Arguments
    /// * `baseline_name` - Name of the baseline (e.g., `cis_lvl1`)
    /// * `profile_paths` - Paths to mobileconfig files
    /// * `script_paths` - Paths to script files (audit, remediate)
    pub fn generate_team_yml(
        &self,
        baseline_name: &str,
        profile_paths: &[PathBuf],
        script_paths: &[(PathBuf, Option<PathBuf>)], // (audit, remediate)
    ) -> Result<PathBuf> {
        self.generate_team_yml_with_policies(baseline_name, profile_paths, script_paths, None)
    }

    /// Generate a fleet YAML file for a specific baseline, optionally including
    /// a policies path reference.
    pub fn generate_team_yml_with_policies(
        &self,
        baseline_name: &str,
        profile_paths: &[PathBuf],
        script_paths: &[(PathBuf, Option<PathBuf>)],
        policy_path: Option<&Path>,
    ) -> Result<PathBuf> {
        let fleets_dir = self.output_base.join(self.layout.fleets_dir);
        std::fs::create_dir_all(&fleets_dir)?;

        let team_name = baseline_name.replace('_', "-");
        let label_name = format!("mscp-{baseline_name}");
        let secret_var = format!(
            "FLEET_{}_ENROLL_SECRET",
            baseline_name.to_uppercase().replace('-', "_")
        );

        // Build custom settings with proper relative paths from fleets/
        let mut custom_settings = Vec::new();
        for profile_path in profile_paths {
            let filename = profile_path
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or_default();

            // Path from fleets/{fleet}.yml to platforms/mscp/{baseline}/profiles/
            let relative_path = format!(
                "../{}/mscp/{baseline_name}/profiles/{filename}",
                self.layout.platforms_dir
            );

            custom_settings.push(CustomSetting {
                path: relative_path,
                labels_include_all: Some(vec![label_name.clone()]),
                labels_include_any: None,
                labels_exclude_any: None,
            });
        }

        // Build scripts with proper relative paths
        let mut scripts = Vec::new();
        for (audit_path, remediate_path) in script_paths {
            let audit_filename = audit_path
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or_default();
            scripts.push(Script {
                path: format!(
                    "../{}/mscp/{baseline_name}/scripts/{audit_filename}",
                    self.layout.platforms_dir
                ),
            });

            if let Some(remediate) = remediate_path {
                let remediate_filename = remediate
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or_default();
                scripts.push(Script {
                    path: format!(
                        "../{}/mscp/{baseline_name}/scripts/{remediate_filename}",
                        self.layout.platforms_dir
                    ),
                });
            }
        }

        // Build fleet settings as yaml_serde::Value
        let team_settings = TeamSettings {
            secrets: Some(vec![EnrollSecret {
                secret: format!("${secret_var}"),
            }]),
            features: Some(Features {
                enable_host_users: Some(true),
                enable_software_inventory: Some(true),
            }),
        };

        // Build policies -- either a path reference to generated policy file, or empty
        let policies_value: Vec<yaml_serde::Value> = if let Some(p) = policy_path {
            let policy_filename = p.file_name().and_then(|s| s.to_str()).unwrap_or_default();
            let relative_policy_path = format!(
                "../{}/mscp/{baseline_name}/policies/{policy_filename}",
                self.layout.platforms_dir
            );

            let mut map = yaml_serde::Mapping::new();
            map.insert(
                yaml_serde::Value::String("path".to_string()),
                yaml_serde::Value::String(relative_policy_path),
            );
            vec![yaml_serde::Value::Mapping(map)]
        } else {
            Vec::new()
        };

        let config = FleetTeamConfig {
            name: Some(team_name.clone()),
            policies: Some(policies_value),
            reports: Some(Vec::new()),
            agent_options: Some(yaml_serde::to_value(AgentOptionsRef {
                path: format!("../{}", self.layout.agent_options_path),
            })?),
            controls: Some(Controls {
                macos_settings: if custom_settings.is_empty() {
                    None
                } else {
                    Some(PlatformSettings {
                        custom_settings: Some(custom_settings),
                    })
                },
                ios_settings: None,
                scripts: if scripts.is_empty() {
                    None
                } else {
                    Some(scripts)
                },
            }),
            settings: Some(yaml_serde::to_value(&team_settings)?),
            software: Some(Software::default()),
        };

        let file_path = fleets_dir.join(format!("{baseline_name}.yml"));

        let header = format!(
            r"# Fleet GitOps - Fleet Configuration: {team_name} (Fleet v4.82+)
#
# mSCP Baseline: {baseline_name}
# Profiles and scripts are in: {platforms_dir}/mscp/{baseline_name}/
#
# Required environment variables:
#   - ${secret_var}
#
# Generated by contour mscp - https://github.com/headmin/contour

",
            platforms_dir = self.layout.platforms_dir,
        );

        let yaml_content = yaml_serde::to_string(&config)?;
        std::fs::write(&file_path, format!("{header}{yaml_content}"))?;

        tracing::info!("Generated fleet YAML: {}", file_path.display());
        Ok(file_path)
    }

    /// Add a label path reference to default.yml using line-based insertion.
    ///
    /// This preserves comments and formatting by inserting directly into the YAML text
    /// rather than round-tripping through serde.
    pub fn add_label_to_default_yml(&self, label_path: &str) -> Result<()> {
        let file_path = self.output_base.join("default.yml");

        if !file_path.exists() {
            anyhow::bail!("default.yml does not exist. Run generate_structure() first.");
        }

        // Read existing content
        let content = std::fs::read_to_string(&file_path)?;

        // Check if already present
        if content.contains(label_path) {
            tracing::info!("Label reference already present in default.yml: {label_path}");
            return Ok(());
        }

        let entry_line = format!("- path: {label_path}");

        // Try line-based insertion
        let new_content = if let Some(result) = insert_label_entry(&content, &entry_line) {
            result
        } else {
            // Fallback: append labels section at end
            let mut result = content.clone();
            if !result.ends_with('\n') {
                result.push('\n');
            }
            result.push_str(&format!("labels:\n  {entry_line}\n"));
            result
        };

        std::fs::write(&file_path, new_content)?;

        tracing::info!("Added label reference to default.yml: {label_path}");
        Ok(())
    }

    /// Generate a fragment-style default.yml containing only labels section.
    ///
    /// This is used in fragment mode where org_settings, agent_options, and controls
    /// are not included (they come from the target repo).
    pub fn generate_fragment_default_yml(&self, label_paths: &[String]) -> Result<PathBuf> {
        let file_path = self.output_base.join("default.yml");

        let mut content = String::from(
            "# Fleet GitOps - Fragment Configuration (labels only)\n\
             #\n\
             # This fragment provides label definitions to be merged into a target repo.\n\
             #\n\
             # Generated by contour mscp - https://github.com/headmin/contour\n\
             \n",
        );

        if label_paths.is_empty() {
            content.push_str("labels:\n");
        } else {
            content.push_str("labels:\n");
            for lp in label_paths {
                content.push_str(&format!("  - path: {lp}\n"));
            }
        }

        content.push_str("\nreports:\n\npolicies:\n");

        std::fs::write(&file_path, &content)?;
        tracing::info!("Generated fragment default.yml: {}", file_path.display());
        Ok(file_path)
    }

    /// Generate a `fragment.toml` manifest at the output root.
    pub fn generate_fragment_toml(
        &self,
        name: &str,
        label_paths: &[String],
        profile_entries: &[contour_core::fragment::ProfileEntry],
        policy_entries: &[contour_core::fragment::SimpleEntry],
        lib_files: &[String],
    ) -> Result<PathBuf> {
        let manifest = contour_core::fragment::FragmentManifest {
            fragment: contour_core::fragment::FragmentMeta {
                name: name.to_string(),
                version: "1.0.0".to_string(),
                description: format!("mSCP baseline: {name}"),
                generator: "contour-mscp".to_string(),
            },
            default_yml: contour_core::fragment::DefaultYmlEntries {
                label_paths: label_paths.to_vec(),
                report_paths: Vec::new(),
                policy_paths: policy_entries.iter().map(|e| e.path.clone()).collect(),
            },
            fleet_entries: contour_core::fragment::FleetEntries {
                profiles: profile_entries.to_vec(),
                reports: Vec::new(),
                policies: policy_entries.to_vec(),
                software: Vec::new(),
            },
            lib_files: contour_core::fragment::LibFiles {
                copy: lib_files.to_vec(),
            },
            scripts: contour_core::fragment::ScriptEntries::default(),
        };

        let file_path = self.output_base.join("fragment.toml");
        manifest.save(&file_path)?;
        tracing::info!("Generated fragment.toml: {}", file_path.display());
        Ok(file_path)
    }

    /// Check if default.yml already exists
    pub fn default_yml_exists(&self) -> bool {
        self.output_base.join("default.yml").exists()
    }

    /// Check if agent-options.yml already exists
    #[allow(dead_code, reason = "reserved for future use")]
    pub fn agent_options_exists(&self) -> bool {
        self.output_base
            .join(self.layout.agent_options_path)
            .exists()
    }

    /// Check if unassigned hosts YAML already exists
    #[allow(dead_code, reason = "reserved for future use")]
    pub fn unassigned_yml_exists(&self) -> bool {
        self.output_base
            .join(self.layout.fleets_dir)
            .join(self.layout.unassigned_filename)
            .exists()
    }
}

/// Insert a label entry line into existing YAML content.
///
/// Finds the `labels:` section and inserts the entry after the last existing
/// `- path:` entry (or right after `labels:` if none exist). Preserves comments
/// and formatting.
fn insert_label_entry(content: &str, entry_line: &str) -> Option<String> {
    let lines: Vec<&str> = content.lines().collect();

    // Find the `labels:` line (top-level, no indentation)
    let labels_idx = lines.iter().position(|l| {
        let trimmed = l.trim();
        trimmed == "labels:" || trimmed.starts_with("labels:")
    })?;

    // Find the indentation to use (look at existing entries under labels:)
    let indent = "  ";

    // Find insertion point: after last `- path:` entry under labels, or right after `labels:`
    let mut insert_idx = labels_idx + 1;
    let mut i = labels_idx + 1;
    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim();

        // Stop if we hit another top-level key
        if !trimmed.is_empty() && !trimmed.starts_with('#') && !line.starts_with(' ') {
            break;
        }

        // Track last label entry position
        if trimmed.starts_with("- path:") {
            insert_idx = i + 1;
        }

        i += 1;
    }

    let mut result = Vec::with_capacity(lines.len() + 1);
    for (idx, line) in lines.iter().enumerate() {
        result.push(line.to_string());
        if idx == insert_idx - 1 {
            result.push(format!("{indent}{entry_line}"));
        }
    }

    // If insert_idx is past the end, append
    if insert_idx >= lines.len() {
        result.push(format!("{indent}{entry_line}"));
    }

    Some(result.join("\n") + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_generate_default_yml() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());

        let path = generator.generate_default_yml().unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("$FLEET_URL"));
        assert!(content.contains("$FLEET_GLOBAL_ENROLL_SECRET"));
        assert!(content.contains(&format!("./{}", FleetLayout::default().agent_options_path)));
    }

    #[test]
    fn test_generate_agent_options() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());

        let path = generator.generate_agent_options().unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("distributed_interval"));
        assert!(content.contains("pack_delimiter"));
    }

    #[test]
    fn test_generate_unassigned_yml() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());

        let path = generator.generate_unassigned_yml().unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        let layout = FleetLayout::default();
        assert!(content.contains(&format!("name: {}", layout.unassigned_name)));
    }

    #[test]
    fn test_generate_team_yml() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let layout = FleetLayout::default();

        let profiles = vec![PathBuf::from("profiles/com.apple.test.mobileconfig")];
        let scripts = vec![(
            PathBuf::from("scripts/test_audit.sh"),
            Some(PathBuf::from("scripts/test_remediate.sh")),
        )];

        let path = generator
            .generate_team_yml("cis_lvl1", &profiles, &scripts)
            .unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("name: cis-lvl1"));
        assert!(content.contains(&format!(
            "../{}/mscp/cis_lvl1/profiles/",
            layout.platforms_dir
        )));
        assert!(content.contains(&format!(
            "../{}/mscp/cis_lvl1/scripts/",
            layout.platforms_dir
        )));
        assert!(content.contains("$FLEET_CIS_LVL1_ENROLL_SECRET"));
    }

    #[test]
    fn test_generate_structure() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new_default(temp_dir.path());
        let layout = FleetLayout::default();

        generator.generate_structure().unwrap();

        assert!(temp_dir.path().join("default.yml").exists());
        assert!(temp_dir.path().join(layout.agent_options_path).exists());
        assert!(
            temp_dir
                .path()
                .join(layout.fleets_dir)
                .join(layout.unassigned_filename)
                .exists()
        );
    }

    #[test]
    fn test_legacy_layout_paths() {
        let temp_dir = TempDir::new().unwrap();
        let generator = FleetGitOpsGenerator::new(temp_dir.path(), FleetLayout::legacy());

        generator.generate_structure().unwrap();

        assert!(temp_dir.path().join("default.yml").exists());
        assert!(temp_dir.path().join("lib/agent-options.yml").exists());
        assert!(temp_dir.path().join("fleets/no-team.yml").exists());

        let content = std::fs::read_to_string(temp_dir.path().join("fleets/no-team.yml")).unwrap();
        assert!(content.contains("name: No team"));
    }
}
